### ISSUE TITLE
[Feature request] Add buffer to monitor values of local variables

### ISSUE THREAD

**Issue by Diadlo** [sakhnik/nvim-gdb#102]
Hello. It will be very useful to have buffer with actual output of `info locals`

**Comment by sakhnik** [comment]
This is already possible, but probably I'd need to add a framework for that. There is an example of how to echo `info locals`: [:help GdbCusomCommand](https://github.com/sakhnik/nvim-gdb/commit/78fcac1c86f4b04150005883398dec9e962dfaa6#diff-3b08d4fc5ac56d63c4eca2d6a9a3c954R222). It just needs to be adjusted to modify a buffer content instead.

**Comment by Diadlo** [comment]
That's interesting. `:help GdbCusomCommand` show me `E149: Sorry, no help for GdbCusomCommand`

**Comment by sakhnik** [comment]
Perhaps messed help tags.

**Comment by Diadlo** [comment]
`:GdbCusomCommand` show error too: `E492: Not an editor command: GdbCusomCommand`

**Comment by sakhnik** [comment]
It's actually a function, so should be called just like in the example above.

**Comment by Diadlo** [comment]
`:GdbCustomCommand('info locals')` -> `E492: Not an editor command: GdbCustomCommand('info locals')`

**Comment by sakhnik** [comment]
@Diadlo, would a suggestion in the doc be enough or do you think a more elaborate solution is needed?

**Comment by Diadlo** [comment]
#### Looks like this command doesn't have any effect on my machine.

1. `nvim main.c`
2. `:GdbStart gdb a.out`
3. Start debugging
4. `:vsplit`
5. `:autocmd User NvimGdbQuery call nvim_buf_set_lines(bufnum, 0, -1, 0, split(GdbCustomCommand("info locals"), "\n"))`

What I'm doing wrong?

#### "Would be enough?"

Depends what do you what from the project :)
I suggest opening (or leave this issue open) issue with the task to create a more elaborate solution

**Comment by sakhnik** [comment]
Did you step through the program after defining the autocmd? The event `NvimGdbQuery` is only issued when GDB prompt is found. If the buffer content doesn't change, what's returned from the functions `GdbCustomCommand`, `split`, `nvim_buf_set_lines` when called manually?

**Comment by Diadlo** [comment]
`:call GdbCustomCommand("info locals")` show nothing
`:echo GdbCustomCommand("info locals")` show output in the status line
`:echo split("1\n2", "\n")` shows `['1', '2']`
`:call nvim_buf_set_lines(bufnum, 0, -1, 0, ['1', '2'])` show:
```
E121: Undefined variable: bufnum                       
E116: Invalid arguments for function nvim_buf_set_lines
```

**Comment by Diadlo** [comment]
If I use `bufnr("%")` instead of `bufnum` it looks like: https://asciinema.org/a/EfABS598u4xxxk5IEdC1T3mi0

**Comment by sakhnik** [comment]
Yes, there is clearly something off. Autocommands are notorious to debug. Could you please check out the branch [autowin](https://github.com/sakhnik/nvim-gdb/tree/autowin) and try the command `GdbCreateWatch`? For example, `:GdbCreateWatch info locals`.

**Comment by Diadlo** [comment]
@sakhnik Yes, this mutch better and also works :)
