### ISSUE TITLE
[Bug] Code buffer not always jumps to the breakpoint

### ISSUE THREAD

**Issue by Diadlo** [sakhnik/nvim-gdb#103]
I'm not sure about steps to reproduce but it seems it only happens when code execution continued from the gdb window and breakpoint placed not in the currently opened file. But after one step (F10 or `n` command) code window jumps fine

**Comment by sakhnik** [comment]
I'm afraid we need to know how to reproduce the issue exactly. When I've just tried it, it worked just well.

**Comment by Diadlo** [comment]
It seems like +/- randomly

**Comment by sakhnik** [comment]
All right, no reproduce means no issue.

**Comment by Diadlo** [comment]
Since when?

**Comment by sakhnik** [comment]
Yes, I completely agree with you. What I meant was I've been working with the plugin for a week while implementing #102, but wasn't able to notice any missed jump. I suspect there could be something specific in your environment or code. Please feel free to reopen the ticket when there is more information available.

**Comment by sakhnik** [comment]
There is a checklist for troubleshooting:
- Does GDB print the location in the source code when the jump didn't happen?
- Is the file reachable by the path reported by GDB?
- Does jump occur when going frame up/down?
