### ISSUE TITLE
Signs are uncleaned when multiple files

### ISSUE THREAD

**Issue by eggeek** [sakhnik/nvim-gdb#107]
[![asciicast](https://asciinema.org/a/FSkEzOg8gDKZjpfxRr3ASlE3J.svg)](https://asciinema.org/a/FSkEzOg8gDKZjpfxRr3ASlE3J)

"Step in" opened another file, and signs were uncleaned after the finish.

Version:
```
commit 9ea1cd2cd110a8efa40dc893036596b39f979a7a (grafted, HEAD -> master, origin/master, origin/HEAD)
Author: Anatolii Sakhnik <sakhnik@gmail.com>
Date:   Tue Mar 17 09:10:21 2020 +0200

    Merge branch 'devel'
```

**Comment by sakhnik** [comment]
Thanks for the report. The bug has been there for ages.
