### ISSUE TITLE
don't launch gdb on windows os

### ISSUE THREAD

**Issue by grimgort** [sakhnik/nvim-gdb#111]
Hello,
I can't get GDB to work under windows. I checked the prerequisites with the sh script. They're good. when I run GdbStart gdb -q t1.exe I get an exit with 0

**Comment by sakhnik** [comment]
It's no surprise because I never tested it in Windows. In fact, GDB is launched in a PTY using `gdb_proxy.py`. As [the documentation](https://docs.python.org/3/library/pty.html) says, it's only supported on Linux.
If the proxy apps could be ported to Windows, so could be the plugin.

**Comment by sakhnik** [comment]
I'm unlikely to get into implementing this.
