### ISSUE TITLE
Cannot run GdbStart: unknown function GdbInit

### ISSUE THREAD

**Issue by SuperCuber** [sakhnik/nvim-gdb#112]
Installed the plugin using vim-plug `Plug 'sakhnik/nvim-gdb', { 'do': ':!./install.sh \| UpdateRemotePlugins' }`

Ran `GdbStart rust-gdb -q target/debug/my_executable` while in my Rust project.

```Error detected while processing function <SNR>16_Spawn:
line    3:
E117: Unknown function: GdbInit
```

Indeed, typing `:Gdb<TAB>` shows the following commands:
```
GdbStart
GdbStartBashDB
GdbStartLLDB
GdbStartPDB
```
Same with completing `:call G<Tab>`, it only completes unrelated stuff.

Same error with just `gdb`. I'm happy to provide more information if needed.

**Comment by sakhnik** [comment]
Could you please check whether Python 3 is supported?
Please run `:checkhealth`, pynvim is required for the plugin to work.
Are there any other errors reported during startup?

**Comment by SuperCuber** [comment]
Python 3 is supported, no other errors in :messages

It happens consistently, even after PlugCleaning and re installing.

**Comment by sakhnik** [comment]
What Python 3 provider does `:checkhealth` report?
Does manual execution of `:UpdateRemotePlugins` help?

**Comment by SuperCuber** [comment]
```
## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/bin/python3
  - INFO: Python version: 3.6.9
  - INFO: pynvim version: 0.4.1
  - OK: Latest pynvim is installed.
```
`:UpdateRemotePlugins` gives this:
```
remote/host: python3 host registered plugins ['gdb']
remote/host: generated rplugin manifest: /home/amit/.local/share/nvim/rplugin.vim
```
Immediately after, error persists, but after restarting nvim it seems to work.
I wonder if the `do` part of the vim-plug installation is happening... I don't know that syntax so I can't tell if it's correct.
I can tell though that during installation it does run some hooks for the plugin. Maybe an escaping issue?

**Comment by sakhnik** [comment]
I see the question was raised for vim-plug already: https://github.com/junegunn/vim-plug/issues/125
I'll have to fix README to ask users to explicitly execute `:UpdateRemotePlugins`.
