### ISSUE TITLE
[Feature Request] Export _define_signs to users

### ISSUE THREAD

**Issue by kevinhwang91** [sakhnik/nvim-gdb#114]
I'm using only one width signcolumn(`signcolumn=yes:1`),  `GdbCurrentLine` and `GdbBreakpoint` seize this precious column.
I'd like to use `numhl` or `linehl` for `GdbCurrentLine` sign attributes rather than `text`.

**Comment by kevinhwang91** [comment]
```vim
autocmd User NvimGdbStart call sign_undefine('GdbCurrentLine') |
            \ call sign_define('GdbCurrentLine', {'numhl': 'Operator'})
```
do what I want.

**Comment by sakhnik** [comment]
@kevinhwang91, that's impressive! Currently, the text sign could be overridden in the user's configuration by the key 'sign_current_line'. And the plugin could in theory support not only text signs.
But I'm glad you found a suitable solution for you.
