### ISSUE TITLE
Source code not displayed

### ISSUE THREAD

**Issue by RealSaltyFish** [sakhnik/nvim-gdb#116]
When I use nvim-gdb to debug my program, the upper split just shows nothing from the beginning to the end.
I use macOS 10.15.7 and latest neovim. Tested on both VimR (a GUI for nvim) and iTerm2. The same for lldb/gdb.

**Comment by sakhnik** [comment]
Apparently, the plugin can't find the source files reported by the debugger. Would you be able to configure logging and collect some logs for your case? You'll need to modify the source code in `lib/base_proxy.py` and `rplugin/python3/gdb/logger.py`.

**Comment by RealSaltyFish** [comment]
> Would you be able to configure logging and collect some logs for your case? You'll need to modify the source code in `lib/base_proxy.py` and `rplugin/python3/gdb/logger.py`.

I see that in `rplugin/python3/gdb/logger.py` there's a handler commented out. I uncommented it and changed `loggers[''].['handlers']` to `['file']`. I then went to `lib/base_proxy.py`, imported the dict `LOGGING_CONFIG` and made the following change:
```python
        # logging.basicConfig(
        #     level=logging.DEBUG,
        #     format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
        #     handlers=[logging.NullHandler()])
        logging.config.dictConfig(LOGGING_CONFIG)
```

but now the debug tab just immediately exits after initialization. The only log I got is:
```
[INFO] Gdb: Cleanup tab=2
[INFO] Gdb: GdbHandleEvent on_tab_enter
```

What did I do wrong?

**Comment by sakhnik** [comment]
You should just substitute `NullHandler` with `FileHandler` in the proxy. Please take a look at the branch `logging` that I just created: https://github.com/sakhnik/nvim-gdb/commit/0d2faeb2b2d8c35258626bae293398f77d0d25ee

**Comment by RealSaltyFish** [comment]
Sorry - I found that if I first set a breakpoint and then issue `run`, the source code appears and everything works normally. Previously I did not set any breakpoint.
Is this the expected behavior? Will it be possible to make the source code appear before setting breakpoints and executing the program?

The log was basically the same if I just run the program without setting a breakpoint.

**Comment by sakhnik** [comment]
All right, there's no bug, the behaviour is expected. I don't think I can to properly determine what should be shown in the jump window initially. When I try the commands `up`, `down`, only `No stack` is output. One could automate typical actions like 'b main; run' when launching the debugger. Then the source would be displayed.
