### ISSUE TITLE
vim-plug failed install

### ISSUE THREAD

**Issue by jeanlucthumm** [sakhnik/nvim-gdb#128]
Got hit with the following after running `:PlugInstall`

![image](https://user-images.githubusercontent.com/4934853/106932829-0dc0cc80-66cd-11eb-8851-1a069ca94671.png)

Plug entry is: `Plug 'sahnik/nvim-gdb', { 'do': ':!./install.sh' }`  as was suggested in the README

**Comment by sakhnik** [comment]
There's a small typo, it should be `sakhnik/nvim-gdb`. Note the missing letter k. I've just checked the README, the spelling is correct there.

**Comment by jeanlucthumm** [comment]
omg so sorry about that!
