### ISSUE TITLE
Can not clear input using `CTRL-U`

### ISSUE THREAD

**Issue by voldikss** [sakhnik/nvim-gdb#130]
# Problem

Sometimes I want to clear my input so I type `<C-u>`, I expect that the command will be cleared from the cursor place up to the begining of the line but it doesn't. Instead, there are several characters at the begining that can not be cleared. See the gif for the detail.
![gdb](https://user-images.githubusercontent.com/20282795/108488272-23dca880-72db-11eb-98de-fc08bec763e2.gif)

But it works normally when I open the gdb directly from the `termopen` function. See the gif below.

![gdb2](https://user-images.githubusercontent.com/20282795/108488261-217a4e80-72db-11eb-9bc7-738f5b373425.gif)

**Comment by sakhnik** [comment]
Interesting, but I can't reproduce the issue. The whole line is cleared for me. Maybe this is terminal or environment-dependent. Could you please try the branch `lua`? Could you please `cd test; CI=1 ./nvim` and try to reproduce the issue again? Could you please collect the log files `*.log` generated?

**Comment by voldikss** [comment]
Must be the problem of my enviroment. Thanks for your attention!
