### ISSUE TITLE
The plugin creates an empty window which blocks my original code view

### ISSUE THREAD

**Issue by voldikss** [sakhnik/nvim-gdb#132]
When executing `:GdbStart`, an empty window is created, which means I have to take more steps to switch to my original buffer. It should be expected that my code window is kept opened during spawning gdb.

![gdb3](https://user-images.githubusercontent.com/20282795/108583209-dd3a8d00-7372-11eb-93a9-6d77717c5ffc.gif)

The issue seems caused by 

https://github.com/sakhnik/nvim-gdb/blob/53fc0cee121ef05e719b1df1beacfe0dc07c4520/rplugin/python3/gdb/app.py#L33-L36

Why use `tabnew`?  could we fix that?

**Comment by sakhnik** [comment]
Thanks, that's a good idea. The tabpage is used to isolate the debugging session. Close the tabpage, and everything is cleaned up.
But it should be rather straight forward to just load the original buffer into the source window in the debugger tabpage upon startup.

**Comment by sakhnik** [comment]
With [neovim-0.5](https://github.com/neovim/neovim/milestone/19) just around the corner, I'm thinking about merging the branch `lua` into `master` very soon. The fix is there for now.

**Comment by rgreenblatt** [comment]
More generally, I think more windowing control would be useful. For instance I would like to be able to open the debugging terminal in the current window and designate a specific window to be the source window. This would allow for more scripting around the window layout.

**Comment by sakhnik** [comment]
@rgreenblatt, I guess it's all not too much complicated, and can be gradually implemented. First, we could allow starting a debugging session on the current tabpage (#137), then allow defining custom layouts (#138).

**Comment by lyh970817** [comment]
It looks like the issue persists when you install by `Plug 'sakhnik/nvim-gdb', { 'do': ':!./install.sh' }`. Do I have to install from the lua branch?

**Comment by lyh970817** [comment]
I'm also curious why this doesn't seem to be a problem in your showcase demo. It looks like in the demo although an empty buffer is opened, it quickly switches back to the original source code automatically.

**Comment by sakhnik** [comment]
Yes, the fix is in the branch `lua` only. I'm expecting neovim-0.5 to be released soon to be able to merge the branch to main then.
The showcase demo does show the issue: a new tabpage is created with an empty source window until the first breakpoint is hit.

**Comment by sakhnik** [comment]
It looks like neovim-0.5 isn't going to be released any soon. So I added a compatibility layer for 0.4.4, and merged into master.
