### ISSUE TITLE
Allow defining custom window layouts

### ISSUE THREAD

**Issue by sakhnik** [sakhnik/nvim-gdb#138]
By @rgreenblatt:

> I think more windowing control would be useful. For instance I would like to be able to open the debugging terminal in the current window and designate a specific window to be the source window. This would allow for more scripting around the window layout.

- [x] Add support for tabpage-local configuration overrides
- [x] Document debugging layout definition and provide examples
- [x] Add automatic tests for some notable layouts (vertical, debugger on top)

**Comment by sakhnik** [comment]
@rgreenblatt, why not the other way around? Let the current window become the source window, and there's a specific configurable command to create the debugging terminal window: https://github.com/sakhnik/nvim-gdb/blob/518b4682d42ca011fa78e2c88dfc57d2504e9e66/lua/nvimgdb/config.lua#L29
It seems natural when I imagine editing a source file and then debugging it navigating in the same window.

**Comment by rgreenblatt** [comment]
> @rgreenblatt, why not the other way around? Let the current window become the source window, and there's a specific configurable command to create the debugging terminal window:
> 
> https://github.com/sakhnik/nvim-gdb/blob/518b4682d42ca011fa78e2c88dfc57d2504e9e66/lua/nvimgdb/config.lua#L29
> 
> 
> It seems natural when I imagine editing a source file and then debugging it navigating in the same window.

Yeah, this makes sense. One thing which isn't covered by this is changing the debugging terminal window command "on the fly". For example maybe you want it above this time, but the default should be below. I think this could be done by editting the global config and then reverting the change after, but that is a bit gross.

**Comment by sakhnik** [comment]
It shouldn't be that bad though. You can just override parts of the configuration in either of the two ways:
https://github.com/sakhnik/nvim-gdb/blob/7d32f088de01ef96cef78e7c81fc99fefbac40ca/doc/nvimgdb.txt#L209
https://github.com/sakhnik/nvim-gdb/blob/7d32f088de01ef96cef78e7c81fc99fefbac40ca/doc/nvimgdb.txt#L234

Now that debugging is launched on the current tabpage, we could allow overriding configuration not only with global variables, but maybe with tab-local variables. Like, `let t:nvimgdb_termwin_command = 'aboveleft new'`.

**Comment by rgreenblatt** [comment]
> It shouldn't be that bad though. You can just override parts of the configuration in either of the two ways:
> https://github.com/sakhnik/nvim-gdb/blob/7d32f088de01ef96cef78e7c81fc99fefbac40ca/doc/nvimgdb.txt#L209
> 
> 
> https://github.com/sakhnik/nvim-gdb/blob/7d32f088de01ef96cef78e7c81fc99fefbac40ca/doc/nvimgdb.txt#L234
> 
> Now that debugging is launched on the current tabpage, we could allow overriding configuration not only with global variables, but maybe with tab-local variables. Like, `let t:nvimgdb_termwin_command = 'aboveleft new'`.

 I forgot about the per item global variable - that's a decent solution. Adding window/tab/local equivalents would also be slightly nicer for various situations.
