### ISSUE TITLE
Using <Leader>dd opens a window which quickly closes

### ISSUE THREAD

**Issue by lyh970817** [sakhnik/nvim-gdb#141]
Using <Leader>dd and the other three start commands opens a window which quickly closes by itself. I installed the plugin through vim-plug following the instructions. I also noticed that only the four 'start' commands are available, but all the other commands, for example, "GdbBreakpointToggle" are not available.

**Comment by lyh970817** [comment]
Just realized I didn't have gdb installed.

**Comment by sakhnik** [comment]
I admit there should be better handling of failures, that's to be fixed.

>only the four 'start' commands are available, but all the other commands, for example, "GdbBreakpointToggle" are not available.

That's a feature.

**Comment by lyh970817** [comment]
Somehow \<leader\>db still doesn't work for .sh files with a flashing window that quickly closes. What might be the issue?
