### ISSUE TITLE
A question of sudo gdb

### ISSUE THREAD

**Issue by hypghzy** [sakhnik/nvim-gdb#143]
Hi, dear developer, I am using MacOS which as far as I know, require sudo gdb to debug a process due to the security protocla. While I am trying to debug my code in nvim, I cannot just use the command :GdbStart gdb -q a.out, which shows sudo: invalid option -- f, could you please advice me a approach that can address that problem?
Regards.

**Comment by sakhnik** [comment]
Hi! There are two options:
- Use lldb, which was specifically supported for macos.
- Create a helper shell script to launch gdb. Example:
```
$ cat gdb.sh
#!/bin/bash
sudo gdb "$@"
$ nvim
:GdbStart ./gdb.sh -q a.out
```

**Comment by hypghzy** [comment]
> Hi! There are two options:
> 
>     * Use lldb, which was specifically supported for macos.
> 
>     * Create a helper shell script to launch gdb. Example:
> 
> 
> ```
> $ cat gdb.sh
> #!/bin/bash
> sudo gdb "$@"
> $ nvim
> :GdbStart ./gdb.sh -q a.out
> ```

Thank you very much for the solutions, I will try to implement one of them to slove my problem.
Thanks again,
best wishes.
