### ISSUE TITLE
EALREADY errors occur frequently

### ISSUE THREAD

**Issue by rgreenblatt** [sakhnik/nvim-gdb#145]
`local/share/nvim/plugged/nvim-gdb/lua/nvimgdb/proxy.lua:98: EALREADY: connection already in progress`
This also occurs on line 85.

This occurs regularly with both gdb and lldb in a variety of situation (running the executable, setting breakpoints, hitting `n` a bunch of times, etc.). 
It occurs on both neovim nightly and the latest release.

If this doesn't reproduce easily, let me know and I can try to make a minimal reproduction.

**Comment by sakhnik** [comment]
I don't seem to recall this. Could you please help me reproduce the issue?
Also, it may be worth collecting log files by launching neovim like this:
```
cd test;
CI=1 ./nvim
```

**Comment by rgreenblatt** [comment]
It looks like this issue happens only when [coc.nvim](https://github.com/neoclide/coc.nvim/) is installed.

Here is an `init.vim` which reproduces the issue
```vim
call plug#begin('~/.local/share/nvim/plugged')
Plug 'sakhnik/nvim-gdb'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
call plug#end()
```
It requires vim-plug (and running `:PlugInstall`). I believe the contents of the `coc-settings.json` don't matter - I can reproduce the issue with an empty `coc-settings.json`.

I have been producing the issue by building the following c++ file:
```cpp
#include <iostream>

int main() {
  for (unsigned i = 0; i < 1000; ++i) {
    std::cout << "a" << std::endl;
  }
}
```
Then, I set a breakpoint (using `:GdbBreakpointToggle`) on `for (...` and `std::cout <<...`.
Then I just run continue a bunch of times in the gdb terminal. The issue usually occurs after continue just a few times.

Here are the corresponding logs. I can't seem to find the error in the logs, so I am not sure how helpful they will be.
[nvimgdb.log](https://github.com/sakhnik/nvim-gdb/files/6417961/nvimgdb.log)
[proxy.log](https://github.com/sakhnik/nvim-gdb/files/6417962/proxy.log)

**Comment by sakhnik** [comment]
I'm still unable to reproduce the issue. Neither do I see anything suspicious in the code in question.
Could you please try the same experiment with the branch [bug145](https://github.com/sakhnik/nvim-gdb/commit/08997337cce3c4322b76373248cb6082965696a2)? I've added a few messages to the log to trace the execution path.

**Comment by rgreenblatt** [comment]
Here are the new logs, I can't seem to see anything of importance in them, but I don't know what to look for.
[nvimgdb.log](https://github.com/sakhnik/nvim-gdb/files/6424728/nvimgdb.log)
[proxy.log](https://github.com/sakhnik/nvim-gdb/files/6424729/proxy.log)

Also, I will probably set up a docker container to aid in reproduction as debugging by github issue is pretty slow.

**Comment by sakhnik** [comment]
There is a sign of disruption, `udp_recv_stop` isn't called in the couple of last times. And that's where `EALREADY` is from: [libuv/udp.c](https://github.com/libuv/libuv/blob/af1a79cf490dc805be8b91d719a6aef4dc8fcf0d/src/unix/udp.c#L1334).
It's not clear how the first failure happens. But what if I misuse lua `assert`? What if it causes the code to break early?
Could you please try again (I pushed another commit)?

**Comment by rgreenblatt** [comment]
That commit seems to solve the problem. Here are the logs (with that commit and no obvious issues):
[nvimgdb.log](https://github.com/sakhnik/nvim-gdb/files/6430140/nvimgdb.log)
[proxy.log](https://github.com/sakhnik/nvim-gdb/files/6430141/proxy.log)


Also, I attempted to reproduce the issue in a docker container, but I haven't yet been able to do so. I believe this is because coc.nvim plugins are global, so whatever plugin is causing the issue is present when I am testing "locally" but not in a docker container (I probably should have realized this could be an issue). I am trying to figure out exactly which plugin is causing the issue.

**Comment by sakhnik** [comment]
I'm glad to hear that. So `assert()` was the cause. It really doesn't matter what was the first failure. The program wouldn't be able to recover after it.
