### ISSUE TITLE
Error when using gt and Gt commands after loading nvim-gdb

### ISSUE THREAD

**Issue by prg318** [sakhnik/nvim-gdb#149]
After enabling nvim-gdb with <leader>dd, I can no longer use the ``gt`` and ``Gt`` commands to move between tabs.  I get the following error message:

``E5108: Error executing lua /home/lukas/.vim/plugged/nvim-gdb/lua/nvimgdb/cursor.lua:49: Vim:E158: Invalid buffer name: -1``

After acknowledging the error message, nvim does change to the requested tab, but I'm not sure why I'm getting this error

I'm using the latest neovim from git

**Comment by sakhnik** [comment]
Thanks for the report!
