### ISSUE TITLE
Feature idea -- column breakpoints

### ISSUE THREAD

**Issue by lanza** [sakhnik/nvim-gdb#150]
lldb supports `breakpoint set --line X --column Y` which will let you choose a specific point in the current line to set a breakpoint. e.g.

```
int a = pickRandomNumberFromRange(getStartNumber(), getMaxNumber())
```

So if you say

```
(lldb) breakpoint set --line 42 --column 52
```

you'll break right before the `call` instruction to `getMaxNumber` instead of a line breakpoint that would stop you before `getStartNumber`. Given that vim can trivially tell you the column number as well this should be pretty easy to offer a `GdbColumnBreakpoint`.

I don't think this feature should be part of the standard `GdbBreakpointToggle`, though, since the user could easily mistakingly put the cursor over a random column depending on their text navigation techniques that'll lead to unexpected columns selected. 

pdb, gdb and bashdb do not seem to support this feature.

**Comment by sakhnik** [comment]
If we assume nvim-gdb is to be backend-agnostic, it provides only basic common features. I believe any specific commands could easily be automated in a user config just like the stock ones: https://github.com/sakhnik/nvim-gdb/blob/53bfce7a254651469ce9577349811bc76d9af46c/autoload/nvimgdb.vim#L49
What do you reckon?
