### ISSUE TITLE
Feature idea -- GdbStartRR

### ISSUE THREAD

**Issue by lanza** [sakhnik/nvim-gdb#151]
[rr](https://github.com/rr-debugger/rr) is a tool to support reverse debugging via recording the entire invocation of a process into a database and then launching a debug server reading from that database that pretends to be actively debugging a live process. gdb then attaches to this process and functions as normal. 

You could add 

```
GdbReverseContinue
GdbReverseFinish
GdbReverseNext
GdbReverseNextInstruction
GdbReverseStep
GdbReverseStepInstruction
```

And to make it easier to run this, you could also automate the running and starting of `rr` via running

```
$ rr record theTargetBinary
$ rr replay -s 50505 -k
```

in the background and attaching to it with 
```
$  gdb '-l' '10000' '-ex' 'set sysroot /' '-ex' 'target extended-remote 127.0.0.1:50505' pathToTrace
```

As a side note, both of the suggestions I just made were things I had half-baked in the old python version. I haven't gotten around to looking at the lua implementation yet to start toying with them there.

**Comment by sakhnik** [comment]
It's really promising, I didn't realize the tool existed. In essence, it could be handled as an extension (a subclass) of GDB. I need to experiment with it a little bit.

Now, executing the plugin in-process has real benefits: #115 for example. On the other hand, Lua is indeed simple, aided in NeoVim by a couple of language servers. So I wouldn't be surprised if it became your asset one day too.

**Comment by lanza** [comment]
Just noticed you implemented this! Thank you!

**Comment by sakhnik** [comment]
Thanks for the idea, it turned out very useful in my work: https://sakhnik.com/2022/07/08/rr.html
