### ISSUE TITLE
[Feature Request] support delve

### ISSUE THREAD

**Issue by kevinhwang91** [sakhnik/nvim-gdb#155]
As a terminal user with neovim, I love the idea of nvim-gdb rather than DAP which is too bloated to me. Has a plan to support delve?

**Comment by sakhnik** [comment]
I haven't considered it. If delve's CLI has a distinct prompt, regular syntax for breakpoints lists, it is quite easy to hook it up.
Would you try adding it as a backend?

**Comment by kevinhwang91** [comment]
I'm learning go recently, I am willing to write delve backend for nvim-gdb if I master go later.

**Comment by sakhnik** [comment]
Delve is supported via DAP:

* https://github.com/mfussenegger/nvim-dap
* https://microsoft.github.io/debug-adapter-protocol/implementors/adapters/

There's no point in adding in avoiding that.
