### ISSUE TITLE
Guess executable name with CMake

### ISSUE THREAD

**Issue by tsjordan-eng** [sakhnik/nvim-gdb#156]
We could use the CMake file API to guess which executable the current file belongs to, then pre-populate the GDB command with that instead of  `GdbStart gdb -q a.out`.

I could implement this if anybody is interested

**Comment by sakhnik** [comment]
That's a good idea! How would you suggest handling the case when there're multiple executable targets or build directories?

**Comment by tsjordan-eng** [comment]
Maybe choose the first, or put them in an autocorrect autocomplete list.

**Comment by sakhnik** [comment]
Yes, I'm interested.

**Comment by tsjordan-eng** [comment]
I thought I could put multiple executables in Vim's `cmdline-completion`, but I don't think I can modify those completions. I'll start by just using the first executable found, but is there a preferred way to choose over multiple selections like with a pop-up window or something?

**Comment by sakhnik** [comment]
I'm not a UX expert, but is there a way to implement `-complete=custom` first?

**Comment by tsjordan-eng** [comment]
That was exactly what I was looking for, thanks! Give my branch a pull and try it out on a CMake project. I also added in some completion for any executables in the directory. #158

**Comment by sakhnik** [comment]
That's impressive indeed! Please note that when there's no cmake build directory, an error is thrown. It's better to be silently ignored instead.
[![asciicast](https://asciinema.org/a/Md23XjRT2Mhja52rGlm71nw5F.svg)](https://asciinema.org/a/Md23XjRT2Mhja52rGlm71nw5F)

**Comment by tsjordan-eng** [comment]
Thanks! It should fail silently now.

**Comment by tsjordan-eng** [comment]
#158 closes this
