### ISSUE TITLE
Support for hardware breakpoints

### ISSUE THREAD

**Issue by BonusPlay** [sakhnik/nvim-gdb#157]
With gdb in mind, `hbreak` support (instead of `break`) would make it possible to debug stuff like custom OS under qemu.

**Comment by sakhnik** [comment]
This may be tricky because my gdb responds: "No hardware breakpoint support in the target". Does `info breakpoints` list hardware breakpoints too? If you set `hbreak` from the terminal window, is it displayed in the source code?
What else would you suggest the plugin could do to support hardware breakpoints?

**Comment by BonusPlay** [comment]
> This may be tricky because my gdb responds: "No hardware breakpoint support in the target".

That's because you need a target which supports them (like GDB).

> Does info breakpoints list hardware breakpoints too?

Yup, example:
```
(gdb) info b
 Num     Type           Disp Enb Address            What
 1       hw breakpoint  keep y   0x000000000010f0d0 in kmain(void*) at kernel/src/main.cpp:18
          breakpoint already hit 1 time
```

> If you set `hbreak` from the terminal window, is it displayed in the source code?

Yup. It works ok.

> What else would you suggest the plugin could do to support hardware breakpoints?

Mostly? A keybind to setup `hbreak` instead of `break` (or maybe toggle?)

**Comment by sakhnik** [comment]
There's a way to create custom mappings atop the plugin. Here's an example: [test/keymap_hooks.vim](https://github.com/sakhnik/nvim-gdb/blob/58ec9e5e69c27e468dfc56af3d90099a397293ec/test/keymap_hooks.vim).
I've just added the missing command `:Gdb` to execute `hbreak` from a mapping.
Would that be sufficient to tweak your configuration?
