### ISSUE TITLE
error while trying to debug python

### ISSUE THREAD

**Issue by kaushiknfs** [sakhnik/nvim-gdb#160]
![image](https://user-images.githubusercontent.com/369865/134812863-4b2ff45d-0854-4a8c-bb7c-b343d70aaabb.png)

while executing leader dp
error on client.lua:20

Please help.
Thanks.

**Comment by kaushiknfs** [comment]
is there some kind of gdb session that i should have started before attempting to debug? can you point me to a right direction please? am a noob.

Thanks.

**Comment by sakhnik** [comment]
I've actually never tried to run the plugin in Windows, but I'd be glad to hear your impression.
So lua failed to determine the path to the plugin. Could you please try hard coding the path in https://github.com/sakhnik/nvim-gdb/blob/66e3d99387e4f936f3a1f4c065438acdab2e93eb/lua/nvimgdb/client.lua#L19 ?

**Comment by sakhnik** [comment]
Well, I don't have that error, but it doesn't actually matter. There's no chance to run the plugin in Windows because the Unix features are used to run the debugger. Specifically, PTY (pseudo-terminal) isn't supported.

**Comment by kaushiknfs** [comment]
Thank you!
