### ISSUE TITLE
Current line not shown when a hardware watch is triggered in GDB

### ISSUE THREAD

**Issue by ammen99** [sakhnik/nvim-gdb#161]
Hello,

I have just set up this plugin and I love it! However, I noticed something strange, when I set up a watchpoint in gdb with `watch <X>` then when `<X>` changes, in the gdb terminal I can of course see that the watched variable has changed. However, in the window where the source code is displayed, the current line is not marked as usual. Is this something by design, missing functionality, or something I have misconfigured? Thanks in advace.

**Comment by sakhnik** [comment]
Hi! I'm not sure whether this is a bug. Could you please record a showcase with asciinema?

**Comment by ammen99** [comment]
Yes, here it is: https://asciinema.org/a/aO29TGEgNXGSGdgDrMRMJfmv7

Before opening vim, I have already compiled the source code with `gcc test.c -o test -g`. Everything else is visible in the recording.

**Comment by sakhnik** [comment]
Thanks, yes, that's a bug. I'll look into it.

**Comment by ammen99** [comment]
@sakhnik I just tested https://github.com/sakhnik/nvim-gdb/commit/505b7b6c044fb4b2d1dbd903bec0024410589719, seems to work, thanks!

**Comment by sakhnik** [comment]
@ammen99, well, I've just discovered that some tests fail in neovim-0.6. I'll need to investigate those failures before officially releasing the fix.
