### ISSUE TITLE
Running GdbStart auto quits on open.

### ISSUE THREAD

**Issue by Sammyalhashe** [sakhnik/nvim-gdb#163]
For reference, this is the command I am running:
`:GdbStart gdb --args ./path/to/my/binary <args...>`

You can tell something automatically happens, but the window immediately closes.  I saw another issue where the person did not have `gdb` installed, I do. I could be misusing the plugin though.

**Comment by sakhnik** [comment]
Is `--args` a legitimate option? I don't see it in the gdb manual. I usually just launch `gdb binary`, then `run <args...>` in the GDB CLI.
Perhaps the error reporting should be improved in this case.

**Comment by sakhnik** [comment]
Take your time. I will only be available after the war.

**Comment by Sammyalhashe** [comment]
Oh my bad dude I'm sorry for the circumstances :( Be well.

**Comment by sakhnik** [comment]
The latest revision should preserve the terminal in case of an unsuccessful launch attempt.
