### ISSUE TITLE
:GdbStart crashes on start

### ISSUE THREAD

**Issue by epixinvites** [sakhnik/nvim-gdb#164]
![20220203-145146](https://user-images.githubusercontent.com/54717060/152294972-5fe42a55-4659-4db4-8177-03ece79364c0.png)

**Comment by sakhnik** [comment]
That's very strange. But I bet that's something with your neovim setup. Does any other lua plugin work for your?
What is your neovim version?

**Comment by epixinvites** [comment]
Yes, every other plugin works except nvim-gdb
```
$ nvim --version
NVIM v0.6.1
Build type: Release
LuaJIT 2.0.5
Compiled by builduser
```
Here's my init.vim -> https://termbin.com/brjn

**Comment by sakhnik** [comment]
Is the issue still reproducible with a minimal config? If you launch neovim with the test script `./nvim` in the plugin's directory `test`?

**Comment by epixinvites** [comment]
Just git cloned and tested it, it worked without a problem. Well I guess it's something wrong with my nvim then.

**Comment by sakhnik** [comment]
I'm glad to hear the results. Unfortunately, I don't have a spare machine at the moment to test your configuration. But may I suggest trying to bisect it? There may be something that spoils the environment.

**Comment by epixinvites** [comment]
Hmmm, you're right, I'll comment out all the plugins and see which one is causing problems.

**Comment by epixinvites** [comment]
Wow, I just commented out every single plugin, uncommented it one by one, now the problem is gone. Are you fucking kidding me.

**Comment by sakhnik** [comment]
Kudos!

**Comment by epixinvites** [comment]
But why?

**Comment by epixinvites** [comment]
Alright, I deleted all my sessions, and seems like I have fixed my problem. Thanks mate!

**Comment by sakhnik** [comment]
Welcome!
