### ISSUE TITLE
No breakpoints signs

### ISSUE THREAD

**Issue by kiddae** [sakhnik/nvim-gdb#166]
However I toggle a breakpoint (from they keymap of from gdb) there are no indicators of the breakpoints as defined by default in the config. It's not a problem with my terminal emulator since it can print them without issues in the help menu. 
The line indicator is shown though.

**Comment by sakhnik** [comment]
Could you please reproduce the issue by launching Neovim from the plugin's directory `test`:
`CI=1 ./nvim`?

**Comment by sakhnik** [comment]
@kiddae, any updates on the issue?

**Comment by kiddae** [comment]
Oops, sorry for that.
It wasn't clear how I should do that.
Should I just run the command or do I also have to replicate the issue from there? Do I provide all of the `.log` files yielded afterwards? Also I noticed that if I changed directory some files were created there but not all, so should I stay in the plug-in directory? A lot of questions, I didn't quite understand how exactly that should have been done, please excuse me.

Also I should probably open another issue for that but when I reload a file using `file out.o` and re-run it the plug-in always opens another window for the buffer with the code, it's slightly annoying and I always have to close gdb before recompiling because of that, losing my breakpoints and displays on the way.

**Comment by sakhnik** [comment]
No worries. I'd like to examine the log files to see how exactly the failure happens. So I'm asking to launch the debugger in a specific way, and then conduct the debugging session up to the point of the failure. I'll need all the log files produced (`nvimgdb.log`, `proxy.log` and `spy_ui.log`).

> when I reload a file using file out.o and re-run it the plug-in always opens another window

I'd appreciate another issue ticket for that with illustrations.
