### ISSUE TITLE
Debugger start regression from 4357472

### ISSUE THREAD

**Issue by davxy** [sakhnik/nvim-gdb#167]
Hey Anatolii. From commit https://github.com/sakhnik/nvim-gdb/commit/4357472e675044222d8ba2f89a95a78fed958560  I'm experiencing a regression wrt debugger first start.

In particular when I start the debugger for the **1st time** I get the following error:

![Screenshot from 2022-05-02 10-25-39](https://user-images.githubusercontent.com/8143589/166206204-38e55d75-d465-416b-a2b7-86c8dd6c5624.png)

If I ignore the error, close the debugger and I restart the debugger the error is not shown and I'm able to debug **but all shortcuts are not working** (F8, F10, etc).

See the video [![asciicast](https://asciinema.org/a/gbRGyGWuPhHP9HpdMwBCMKP96.svg)](https://asciinema.org/a/gbRGyGWuPhHP9HpdMwBCMKP96)

**Comment by sakhnik** [comment]
Hi Davide, what version of Neovim are you using? That change utilizes the new API from the recently released 0.7.

**Comment by davxy** [comment]
I'm using Debian Sid (unstable) and at the moment we are at v0.6.1... Stable is still at 0.4 :-)
See [here](https://packages.debian.org/search?keywords=neovim&searchon=names&suite=all&section=all)

From what I can see at the moment both [Ubuntu](https://packages.ubuntu.com/search?keywords=neovim&searchon=names&suite=jammy&section=all) and [Fedora](https://packages.fedoraproject.org/pkgs/neovim/neovim/) stable ship with 0.6.1 as well.

So today your change may impact a lot of people (maybe almost everyone not using Arch or NixOs :-D )

What you suggest? Maybe the change requiring v0.7 can wait a couple of months?  Or maybe there is a workaround?

**Comment by sakhnik** [comment]
There're lots of ways. First of all, anyone could just use an official appimage, or revert the last merge commit in the local plugin repo. The plugin is only tested against the latest version of Neovim.
But I see your point and there's no need to push everyone. So I'm going to revert the last change for now.

**Comment by davxy** [comment]
Indeed I was using the commit before the one I've mentioned. But as you can imagine a lot of people is using your plugin via a plugin manager that pulls directly from master.

Maybe you can keep this issue open just to remember to restore the modifications once that the major distros switched to 0.7?
I'll keep you informed as soon as v0.7 is in the upstream for Debian Testing/Ubuntu/Fedora.

Thank you for the revert :-D Your plugin is awesome ;-)

**Comment by sakhnik** [comment]
No worries, it just occurred to me that maybe we could maintain a couple of branches like `still` and `fresh`. The first one fetched by default should be suitable for everybody, the latter rather for evolution.
Take care!
