### ISSUE TITLE
Couldn't start debugging due to 'Permission denied' exception

### ISSUE THREAD

**Issue by RuoXian233** [sakhnik/nvim-gdb#174]
What are the steps to reproduce this issue?
-------------------------------------------
1. …emm Yep, I think the state I'm facing is kind of odd
2. …My plugin manager is packer.nvim, I installed it by adding “using 'sakhink/nvim-gdb”
3.  It works but I couldn't start debugging whatever C++ or python
What happens?
-------------
I typed the command ":GdbStart gdb -q demo.exe" as the helping documentation, but I got an error
I also tried to type ":GdbStartPDB python -m pdb main.py" to debug a python file, but I got the same error (Note: But I caught a python runtime error in the debug window, it said 'No module named fnctl', I tried to use pip, but it reported that pip could not find this library)

What were you expecting to happen?
----------------------------------
…

Any logs, error output, etc?
----------------------------
Error detected while processing function <lambda>42[1]..nvimgdb#ExitTerm:
line    4:
E5108: Error executing lua ...a\site\pack\packer\start\nvim-gdb/lua/nvimgdb/client.lua:63: C:\Users\12611\AppData\Local\Temp/nvimgdb-sock-rcS902: Permission denied
stack traceback:
        [C]: in function 'assert'
        ...a\site\pack\packer\start\nvim-gdb/lua/nvimgdb/client.lua:63: in function 'cleanup'
        ...data\site\pack\packer\start\nvim-gdb/lua/nvimgdb/app.lua:121: in function 'cleanup'
        ...vim-data\site\pack\packer\start\nvim-gdb/lua/nvimgdb.lua:105: in function 'func'
        ...vim-data\site\pack\packer\start\nvim-gdb/lua/nvimgdb.lua:81: in function 'with_saved_hidden'
        ...vim-data\site\pack\packer\start\nvim-gdb/lua/nvimgdb.lua:97: in function 'cleanup'
        [string "luaeval()"]:1: in main chunk

To obtain the logs (`nvimgdb.log`, `proxy.log`, `spy_ui.log`), launch neovim as follows:
`cd <plugin_dir>/test; CI=1 ./nvim`

If it’s long, please paste to https://gist.github.com/ and insert the link here.

Any other comments?
-------------------

**Comment by sakhnik** [comment]
Unfortunately, Windows isn't supported. Several POSIX APIs are used in the plugin: PTY, sockets to name. Sorry.
