### ISSUE TITLE
Overwrite default mappings

### ISSUE THREAD

**Issue by ploth** [sakhnik/nvim-gdb#18]
How to overwrite the default mappings for `<Leader>dd` and ` <Leader>dl` ?

 I don't want to remove `./a.out` all of the time.
This did not work

```vim
nnoremap <leader>dd :GdbStart gdb -q -f
nnoremap <leader>dl :GdbStartLLDB lldb
```

**Comment by sakhnik** [comment]
Well, I agree that the default keymaps aren't necessarily suitable for everybody, so they can now be suppressed by setting the global variable `let g:nvimgdb_disable_start_keymaps = 1`.
Then you can define your own mapping of the same keystrokes if needed.
