### ISSUE TITLE
Error using lldb

### ISSUE THREAD

**Issue by leosmaia21** [sakhnik/nvim-gdb#181]
Hello , i am new to this plugin and when i use lldb show this error 
Error executing vim.schedule lua callback: ....local/share/nvim/plugged/nvim-gdb/lua/nvimgdb/proxy.lua:48: bad argument #1 to 'lines' (/tmp/nvimgdb-sock-UXlfAL/port: No such
 file or directory)
stack traceback:
        [C]: in function 'lines'
        ....local/share/nvim/plugged/nvim-gdb/lua/nvimgdb/proxy.lua:48: in function '_ensure_connected'
        ....local/share/nvim/plugged/nvim-gdb/lua/nvimgdb/proxy.lua:72: in function 'query'
        ...share/nvim/plugged/nvim-gdb/lua/nvimgdb/backend/lldb.lua:47: in function 'query_impl'
        ...l/share/nvim/plugged/nvim-gdb/lua/nvimgdb/breakpoint.lua:80: in function 'query'
        ...o/.local/share/nvim/plugged/nvim-gdb/lua/nvimgdb/win.lua:283: in function 'query_breakpoints'
        ...are/nvim/plugged/nvim-gdb/lua/nvimgdb/parser_actions.lua:39: in function 'query_breakpoints'
        .../share/nvim/plugged/nvim-gdb/lua/nvimgdb/parser_impl.lua:116: in function 'handler'
        .../share/nvim/plugged/nvim-gdb/lua/nvimgdb/parser_impl.lua:169: in function '_search'
        .../share/nvim/plugged/nvim-gdb/lua/nvimgdb/parser_impl.lua:189: in function 'delay_elapsed'
        .../share/nvim/plugged/nvim-gdb/lua/nvimgdb/parser_impl.lua:147: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>

**Comment by sakhnik** [comment]
Could you please run neovim with the environment variable `CI=1` and collect the log files nvimgdb.log, proxy.log?

**Comment by leosmaia21** [comment]
Hello, i just found this one

[nvimgdb.log](https://github.com/sakhnik/nvim-gdb/files/10051087/nvimgdb.log)

**Comment by sakhnik** [comment]
What happens when you run in the terminal the following command?
```
/home/leonardo/.local/share/nvim/plugged/nvim-gdb/lib/lldb_wrap.sh -a /tmp/lldb-port -- lldb`
```

**Comment by leosmaia21** [comment]
The output was
error: module importing failed: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/leonardo/.local/share/nvim/plugged/nvim-gdb/lib/lldb_commands.py", line 14, in <module>
    def _enum_breaks(debugger: lldb.SBDebugger):
AttributeError: module 'lldb' has no attribute 'SBDebugger'

**Comment by sakhnik** [comment]
It looks like your lldb doesn't support/expose the required python capabilities.

**Comment by sakhnik** [comment]
@leosmaia21, did you find out what was wrong with lldb?

**Comment by leosmaia21** [comment]
No i will just use gdb instead, thank you for the plugin and help!!
