### ISSUE TITLE
Is it possible to disable default keybindings?

### ISSUE THREAD

**Issue by WhiteBlackGoose** [sakhnik/nvim-gdb#182]
Hello!

Thanks for this plugin! Playing with it right now.

However, is it possible to disable the default keybindings?

**Comment by sakhnik** [comment]
Hi. For sure, it's possible in multiple ways. For example, you could specify the whole configuration dictionary:
```
let g:nvimgdb_config = {}
  \ 'sign_current_line': '▶',
  \ 'sign_breakpoint': [ '●', '●²', '●³', '●⁴', '●⁵', '●⁶', '●⁷', '●⁸', '●⁹', '●ⁿ' ],
  \ 'sign_breakpoint_priority': 10,
  \ 'termwin_command': 'belowright new',
  \ 'codewin_command': 'new',
  \ 'set_scroll_off': 5,
  \ 'jump_bottom_gdb_buf': v:true,
  \ }
```
Or maybe just override some configuration keys. The details are available online `:h NvimgdbVariables`.
