### ISSUE TITLE
Error detected while processing TabLeave Autocommands for "*" on tabnew: GdbStartPDB

### ISSUE THREAD

**Issue by benjaminchristie** [sakhnik/nvim-gdb#185]
What are the steps to reproduce this issue?
-------------------------------------------
1. Open `hello.py` using the attached `test_init.vim` file with `nvim -u test_init.vim hello.py`.
2. Start PDB with `:GdbStartPDB python -m pdb %`.
3. Open a new tab with `:tabnew` (which moves from current window to new empty tab).
4. Switch back to PDB tab, and attempt to move back to blank tab

What happens?
-------------
See attached error output.

What were you expecting to happen?
----------------------------------
Clean window change between tabs.

Any logs, error output, etc?
----------------------------
Error output: 
Error detected while processing TabLeave Autocommands for "*":
E5108: Error executing lua ...ocal/share/nvim/plugged/nvim-gdb/lua/nvimgdb/keymaps.lua:66: E31: No such mapping
stack traceback:
        [C]: in function 'nvim_buf_del_keymap'
        ...ocal/share/nvim/plugged/nvim-gdb/lua/nvimgdb/keymaps.lua:66: in function <...ocal/share/nvim/plugged/nvim-gdb/lua/nvimgdb/keymaps.lua:61>
        ...ocal/share/nvim/plugged/nvim-gdb/lua/nvimgdb/keymaps.lua:99: in function '_dispatch'
        ...ocal/share/nvim/plugged/nvim-gdb/lua/nvimgdb/keymaps.lua:112: in function 'dispatch_unset'
        ...n/.local/share/nvim/plugged/nvim-gdb/lua/nvimgdb/app.lua:277: in function 'on_buf_leave'
        ...n/.local/share/nvim/plugged/nvim-gdb/lua/nvimgdb/app.lua:251: in function 'on_tab_leave'
        [string ":lua"]:1: in main chunk

Link to logs and test files: https://gist.github.com/benjaminchristie/b49efc5dff010a4af26aae2526701c38

**Comment by sakhnik** [comment]
Interestingly, I can't reproduce the issue with the same actions and init file.
Regarding the proposed PR https://github.com/sakhnik/nvim-gdb/pull/186, the design is that the plugin should be aware of what mappings it sets so it shouldn't be needed to verify with the Neovim state before unsettling them. So I'd like to understand what exactly happens and why.
I've just updated automatic tests to pass in the modern environment. Then I'd like to look through the logs to investigate a bit.

**Comment by benjaminchristie** [comment]
Strange. I am on v0.9.0. This also happens with an empty config without setting config_override. Could wrap `buf_del_keymap` in `pcall(..)`, like what is done for Win:unset_keymaps.

**Comment by sakhnik** [comment]
Well, I've reproduced the issue now. The key point is to switch the tabpage when the cursor is in the source code window.
The fact that it can't remove a mapping means that it wasn't set in the first place. That's the real issue. I'm going to look into that.
The other `pcall()` must be masking something unwanted too.

**Comment by benjaminchristie** [comment]
I think this is due to`on_buf_leave` is being called before `on_tab_leave`, since "BufLeave" is triggered before "TabLeave" in the autocmd-event hierarchy.

**Comment by sakhnik** [comment]
That's right. But there's a reason to handle `TabLeave` as well. I'm inclined to agree that `pcall()` is the best way to fix the issue. There's no need to check whether the mapping is set in this case. Could you please update the patch?

**Comment by benjaminchristie** [comment]
Updated PR.
