### ISSUE TITLE
Unknown sign: GdbBreakpoint0 after merging d7504a52e3f5f1b6d7f62a006646681bde65a310

### ISSUE THREAD

**Issue by Alexey104** [sakhnik/nvim-gdb#188]
What are the steps to reproduce this issue?
-------------------------------------------
1. `:GdbStart gdb -q ./program`
2. `start`
3. `break some_object::some_method()`
4. `continue`

What happens?
-------------
nvim-gdb crashes:
```
Error executing vim.schedule lua callback: Vim:E155: Unknown sign: GdbBreakpoint0
stack traceback:
        [C]: in function 'sign_place'
        .../alexey/.vim/plugged/nvim-gdb/lua/nvimgdb/breakpoint.lua:65: in function '_set_signs'
        .../alexey/.vim/plugged/nvim-gdb/lua/nvimgdb/breakpoint.lua:82: in function 'query'
        /home/alexey/.vim/plugged/nvim-gdb/lua/nvimgdb/win.lua:283: in function 'query_breakpoints'
        ...xey/.vim/plugged/nvim-gdb/lua/nvimgdb/parser_actions.lua:39: in function 'query_breakpoints'
        ...alexey/.vim/plugged/nvim-gdb/lua/nvimgdb/parser_impl.lua:116: in function 'handler'
        ...alexey/.vim/plugged/nvim-gdb/lua/nvimgdb/parser_impl.lua:169: in function '_search'
        ...alexey/.vim/plugged/nvim-gdb/lua/nvimgdb/parser_impl.lua:189: in function 'delay_elapsed'
        ...alexey/.vim/plugged/nvim-gdb/lua/nvimgdb/parser_impl.lua:147: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

What were you expecting to happen?
----------------------------------
The program should continue the execution until the breakpoint.

Any logs, error output, etc?
----------------------------
I really want this report to be useful, but, unfortunately, I cannot share any of the `nvimgdb.log`, `proxy.log` or `spy_ui.log`. The code I am working on is not my personal project but a proprietary code related to my job, and I am strictly forbidden to share any logs containing even small parts of this code. Sorry:(

Any other comments?
-------------------
The issue occurs with neovim v0.9.0 with any commit including d7504a52e3f5f1b6d7f62a006646681bde65a310 and later, but no any problems at all with earlier commits. I currently use 3c3511affd2fa07bac2cf97854f17630b949ba10, and everything works just fine. If you just go throughout the code step-by-step using `next` or `step` commands, everything is fine, but if you let the program run freely using `continue`, `until` or `finish`, nvim-gdb crashes when breakpoints at certain places of code is reached (not all breakpoints lead to crash, but I have a couple of class methods such that if I set a breakpoint at any of these methods and `continue` until this breakpoint, nvim-gdb will always crash). 

I am really sorry for not being able to provide additional logs.

**Comment by sakhnik** [comment]
Thanks for the report. I'm unable to reproduce the issue because it is specific to the debugged code. I suggest bisecting the issue by exploring beyond the merge commits and trying to identify the root cause.

**Comment by Alexey104** [comment]
I apologize for wasting your time, this is the false report. The issue was not in nvim-gdb itself, but in my `~/.gdbinit`. I used this fancy thing called "gdb-dashboard" which adds tons of python stuff to gdb config. After throwing it out of my `~/.gdbinit` the issue is not reproducible anymore.
