### ISSUE TITLE
Keymaps are overwritten

### ISSUE THREAD

**Issue by sakhnik** [sakhnik/nvim-gdb#19]
Taken from the issue's #14 [comment](https://github.com/sakhnik/nvim-gdb/issues/14#issuecomment-395044181):

After starting nvim I usually press `ctrl - p` to search for the file I want to edit.
`:map <C-p>` results in the following output: `n <C-P> * :FZF<CR>`
Typing `:GdbStart gdb -q -f <mybinary>` starts the the TUI like environment in a new tab.
After my debug session I write quit in the debuggers console. It is not necessary to do anything. Writing quit instantly results in the same issue.
This results in switching to my previous tab where I edited my file.
All keymaps are overwritten from now on.
`:map <C-p>` results in the following output: `No mapping found`

These are my settings for this plugin:
```
" nvim-gdb ((((((((((((((((((((((((((((((((((((((((((((((((
" gdb and lldb wrapper
Plug 'sakhnik/nvim-gdb'
let g:nvimgdb_disable_start_keymaps = 1
" nvim-gdb ))))))))))))))))))))))))))))))))))))))))))))))))
```
PS: Had the same issue before setting `let g:nvimgdb_disable_start_keymaps = 1`

**Comment by sakhnik** [comment]
Made keymaps local to a buffer and transient, i.e., defined temporarily whenever a buffer is entered, and undefined whenever the buffer is left. There is still a small probability that another plugin's local keymaps are cleared. A possible solution could be to remember the original keymaps: https://vi.stackexchange.com/questions/7734/how-to-save-and-restore-a-mapping
But really the simplest one could be to merely define distinctive mappings.
@ploth, FYI.

**Comment by ploth** [comment]
Works fine! Thank you
