### ISSUE TITLE
'GdbStart...' error if delete buffer at event 'NvimGdbCleanup'

### ISSUE THREAD

**Issue by GyouzaRu** [sakhnik/nvim-gdb#190]
What are the steps to reproduce this issue?
-------------------------------------------
1. I write functions to create and destory window about `info locals` when `NvimGdbStart` and `NvimGdbCleanup`.
2. The first time to debug, everything is OK.
3. The second time to call `:GdbStart gdb -q xx.out`, error happens.

What happens?
-------------
1. I would like to open a window to watch loacl variable when starting debug, so I write two functions.
These two functions help me to create and destory window when necessary.
```lua
local win_ID_code_view
local win_ID_gdb_terminal
local win_ID_local_variable

-- call this when NvimGdbStart
GdbSessionInit = function()
  win_ID_gdb_terminal = vim.api.nvim_get_current_win()

  -- jump to code view and disable relativenumber
  vim.api.nvim_command(":wincmd w")
  win_ID_code_view  = vim.api.nvim_get_current_win()
  if vim.wo.relativenumber then
    vim.wo.relativenumber = false
  end

  -- create window to watch local variable
  vim.api.nvim_command(":belowright GdbCreateWatch info locals")

  -- go to local variable win
  while vim.api.nvim_get_current_win() == win_ID_code_view or
    vim.api.nvim_get_current_win() == win_ID_gdb_terminal do
    vim.api.nvim_command(":wincmd w")
  end

  -- get local variable win ID and set it to 10 height
  win_ID_local_variable = vim.api.nvim_get_current_win()
  vim.api.nvim_command(":resize 10")

  -- move cursor back to gdb terminal
  vim.api.nvim_set_current_win(win_ID_gdb_terminal)
end

-- call this when NvimGdbCleanup
GdbSessionEnd = function()
  -- if code view is not relativenumber, set to relativenumber
  vim.api.nvim_set_current_win(win_ID_code_view)
  if vim.wo.relativenumber == false then
    vim.wo.relativenumber = true
  end
  vim.api.nvim_command(":bd! info locuals")
end

vim.cmd([[
  autocmd User NvimGdbStart :lua GdbSessionInit()
  autocmd User NvimGdbCleanup :lua GdbSessionEnd()
]])
```

3. First time to debug is OK. But when the second time to debug: `GdbStart gdb -q xx.out`. Error happened.
```lua
Error executing vim.schedule lua callback: .../share/nvim/lazy/nvim-gdb/lua/nvimgdb/parser_actions.lua:41: Vim(call):E5555: API call: Invalid buffer id: 6
stack traceback:
[C]: in function 'cmd'
.../share/nvim/lazy/nvim-gdb/lua/nvimgdb/parser_actions.lua:41: in function 'query_breakpoints' 
...cal/share/nvim/lazy/nvim-gdb/lua/nvimgdb/parser_impl.lua:116: in function 'handler'
...cal/share/nvim/lazy/nvim-gdb/lua/nvimgdb/parser_impl.lua:169: in function '_search'
...cal/share/nvim/lazy/nvim-gdb/lua/nvimgdb/parser_impl.lua:189: in function 'delay_elapsed' 
...cal/share/nvim/lazy/nvim-gdb/lua/nvimgdb/parser_impl.lua:147: in function ''
vim/_editor.lua: in function <vim/_editor.lua:0>
Press ENTER or type command to continue
```
And I am not able to debug any more. Only restart nvim can fix this.

4. It seems that my behavior about destorying buffer in function `GdbSessionEnd`  causes this problem. If I comment the code `vim.api.nvim_command(":bd! info locuals")` in function `GdbSessionEnd` and delete this buffer manually. This problem will not duplicate.

What were you expecting to happen?
----------------------------------
I would like to automatically create and destory the `info locals` buffer.

Any logs, error output, etc?
----------------------------
Please refer to information above.

If it’s long, please paste to https://gist.github.com/ and insert the link here.

Any other comments?
-------------------
I am not samiliar with lua. Maybe there is some problems in my code. Would it possible to help me find it. Thanks!

**Comment by sakhnik** [comment]
Hello, thanks for reporting! Apart from a typo in your code `locuals`, it should work. I'm fixing up the plugin and please let me know if there's still an error.

**Comment by GyouzaRu** [comment]
Hello, I have tested and everything is OK. I really appreciate your quick resolution of this bug.
