### ISSUE TITLE
gdb attach mode

### ISSUE THREAD

**Issue by winter-loo** [sakhnik/nvim-gdb#197]
how could I use this plugin to attach to a running process?

On command line, I could issue a shell command:

```shell
gdb -p 12345
```

or inside gdb shell:

```
(gdb) attach 12345
```

It seems that this plugin does not have gdb-attach feature yet.

**Comment by sakhnik** [comment]
Doesn't this work?

`:GdbStart gdb -p 12345`

Or just `:GdbStart gdb` then `attach 12345` in the gdb CLI?
