### ISSUE TITLE
My environment breaks the plugin

### ISSUE THREAD

**Issue by ordinary-slim** [sakhnik/nvim-gdb#198]
My setup is breaking the plug-in. Used this pluging without issues for a bit more than a year. After a recent environment update, I get this error when I run `:Gdbstart gdb -q`

```
  Traceback (most recent call last):
    File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
      self.run()
    File "/usr/lib/python3.8/threading.py", line 870, in run
      self._target(*self._args, **self._kwargs)
    File "/home/hohoho/.config/nvim/plugged/nvim-gdb/lib/gdb_commands.py", line 50, in _server
      data, addr = sock.recvfrom(65536)
  socket.timeout: timed out
```
The UI is not working properly after this error i.e. setting a breakpoint doesn't show a bullet nor vim automatically switches to the right file when the breakpoint is reached.

Running pdb works fine.

I tried running the log utilities in the test folder but the 'spy_ui.log' file doesn't give useful information. Any idea what this might be? Thank you in advance, sorry for the vague issue. Let me know how I can give you more information.

**Comment by sakhnik** [comment]
Thanks for reporting. This must have been a bug, which went unnoticed in the environments I use in testing.

**Comment by ordinary-slim** [comment]
Thank you! Works fine now.
