### ISSUE TITLE
showing variables when debugging with bashdb 

### ISSUE THREAD

**Issue by Maziar123** [sakhnik/nvim-gdb#202]
I usually start debugging with nvim-gdb cmd: gdbstartbashdb bash aa.sh

Now you can try to see the local variable va watch then: GdbCreatewatch info locals.

But info locals show:
** unknown info subcommand: locals:  ......

What is the best way to see variables in bash debug?

**Comment by sakhnik** [comment]
I could only suggest exploring help pages of bashdb or its source code, because I myself don't know the answer.
For what it's worth, I only found `info variables`, which lists a lot of them. I'm not sure there are local variables in bash anyway.

**Comment by Maziar123** [comment]
but how info variables in debug with this plugin ?

**Comment by sakhnik** [comment]
The idea is to have full access to the underlying debugger CLI. So I'd just type the command `info variables` there. Or even `echo $myvar`. Maybe it's possible to create a watch window with these commands, but I've never tried with BashDB.
