### ISSUE TITLE
[Question] unable to run lldb on Mac

### ISSUE THREAD

**Issue by qlibp** [sakhnik/nvim-gdb#203]
What are the steps to reproduce this issue?
-------------------------------------------
1. macOS, vim v0.8.3, nvim-gdb, using lldb
2. nvim-gdb commit hash: c8feb2dbcc98164f947a10230825360c5c936d68
3. launching GdbStartlldb with a hello world c++ executable, compiled with g++ 

What happens?
-------------
Terminal ouput Process exit 1, therefore  I have no way to add breakpoints to rerun it again.
[nvimgdb.log](https://github.com/sakhnik/nvim-gdb/files/12902365/nvimgdb.log)

Any other comments?
-------------------
Just want to know what am I doing wrong. Thx

**Comment by sakhnik** [comment]
I guess you need to launch with lldb in the command line: `:GdbStartLLDB lldb ./test`

**Comment by qlibp** [comment]
Holy... You're totally correct! Thx for help!
