### ISSUE TITLE
"Break" in command line history pdb

### ISSUE THREAD

**Issue by bluss** [sakhnik/nvim-gdb#205]
What are the steps to reproduce this issue?
-------------------------------------------
1. Run with pdb
2. Hit a breakpoint and step one instruction
3. Use the command line

What happens?
-------------
There's a break as the most recent command

What were you expecting to happen?
----------------------------------
I know this break is inserted silently automatically, and it would best be hidden from command line history so it doesn't show up as the first up-arrow history.

Any logs, error output, etc?
----------------------------

Any other comments?
-------------------

**Comment by sakhnik** [comment]
This may be a limitation in the implementation. If there were a way to execute a command without showing it in the history, I'd take it. Like in GDB, for example by prefixing the command with the keyword `service`.

By the way, I'd recommend trying out [nvim-dap](https://github.com/mfussenegger/nvim-dap) and [nvim-dap-python](https://github.com/mfussenegger/nvim-dap-python).
