### ISSUE TITLE
Too many arguments for function

### ISSUE THREAD

**Issue by qiuqiufrank** [sakhnik/nvim-gdb#27]
When i started it by ":GdbStart gdb -q -f a.out",i got errors bleow:
Error detected while processing function nvimgdb#Spawn[1]..<SNR>98_InitMachine:                                                                                              
line   20:                                                                                                                                                                   
E118: Too many arguments for function: function                                                                                                                              
E15: Invalid expression: function("s:GdbPaused_continue", data)                                                                                                              
line   21:                                                                                                                                                                   
E118: Too many arguments for function: function                                                                                                                              
E15: Invalid expression: function("s:GdbPaused_jump", data)                                                                                                                  
line   22:                                                                                                                                                                   
E118: Too many arguments for function: function                                                                                                                              
E15: Invalid expression: function("s:GdbPaused_info_breakpoints", data)                                                                                                      
line   23:                                                                                                                                                                   
E118: Too many arguments for function: function                                                                                                                              
E15: Invalid expression: function("s:GdbPaused_breakpoint", data)                                                                                                            
line   26:                                                                                                                                                                   
E118: Too many arguments for function: function                                                                                                                              
E15: Invalid expression: function("s:GdbRunning_pause", data)

**Comment by sakhnik** [comment]
I've never experienced such errors. What version of neovim are you using?

**Comment by sakhnik** [comment]
Searching in Google, the suggestion to similar issues was to just upgrade neovim. You are likely to run the version 0.2.0. While 0.2.1 already should have the issue fixed.

**Comment by qiuqiufrank** [comment]
Works like a charm.Thanks a lot!
