### ISSUE TITLE
Consider supporting dlv

### ISSUE THREAD

**Issue by zhoupro** [sakhnik/nvim-gdb#36]
a dlv wrapper would be useful.

**Comment by sakhnik** [comment]
I totally agree. However, I've never worked with it, neither programmed in Go.
So probably I just need to document the backend interface thoroughly, and someone would be able to integrate new backends easier then.

**Comment by zhoupro** [comment]
The plugin is so awesome. I use it to debug  some c program like redis. The experience is best. Thank you for your great job.  I will try to make a go wrapper as soon as possible.
