### ISSUE TITLE
how can can I make the cursor position fixed

### ISSUE THREAD

**Issue by zhoupro** [sakhnik/nvim-gdb#37]
[
<img width="1082" alt="2018-10-09 6 17 32" src="https://user-images.githubusercontent.com/10397021/46663247-2fd6dc80-cbf0-11e8-8858-f78eedf39a4f.png">
](url)

I want to see code below and before the cursor. But when I debug,the cursor will be the bottom. Can I have method to control the cursor position? tks.

**Comment by sakhnik** [comment]
That's a good idea. You could set the option `scrolloff` to a positive number to keep the cursor off the edges. Consider using `setlocal scrolloff=5` to make the change local to the window.
Could you please prepare a pull request?

**Comment by zhoupro** [comment]
https://github.com/sakhnik/nvim-gdb/pull/38 Please check the pr, tks.

**Comment by voldikss** [comment]
The problem still exists for me. Can anyone please reproduce it?

**Comment by sakhnik** [comment]
Thanks for the report! I think I understand the issue. The option 'scrolloff' only handles the cursor. So we just need to let the cursor follow the current line sign.

**Comment by voldikss** [comment]
The `scrolloff` is set only the first time the code window is opened(BufEnter event is fired and the code related to `set scrolloff` is executed). After that the cursor won't enter the code window again, correspondingly the BufEnter event won't be fired.

**Comment by voldikss** [comment]
Hi @sakhnik Have you found the solution of this problem?

I've made a patch which basically works 

```patch
diff --git a/autoload/nvimgdb.vim b/autoload/nvimgdb.vim
index 71673f0..4fb1c66 100644
--- a/autoload/nvimgdb.vim
+++ b/autoload/nvimgdb.vim
@@ -99,3 +99,18 @@ function! nvimgdb#GlobalCleanup()
   delcommand GdbLopenBacktrace
   delcommand GdbLopenBreakpoints
 endfunction
+
+function! nvimgdb#KeepCursor(winid) abort
+  let curr = win_getid()
+  noa keepalt call win_gotoid(a:winid)
+  let wininfo = getwininfo(a:winid)[0]
+  let botline = wininfo['botline']
+  let topline = wininfo['topline']
+  let currlnum = line('.')
+  let lastlnum = line('$')
+  if botline - topline > &scrolloff && botline - currlnum < &scrolloff && botline < lastlnum
+    let topline += &scrolloff - (botline - currlnum)
+    call winrestview({'topline': topline})
+  endif
+  noa keepalt call win_gotoid(curr)
+endfunction
diff --git a/rplugin/python3/gdb/win.py b/rplugin/python3/gdb/win.py
index 87d453c..a7ee547 100644
--- a/rplugin/python3/gdb/win.py
+++ b/rplugin/python3/gdb/win.py
@@ -84,7 +84,11 @@ class Win(Common):
         # Ensure the jump window is available
         with self._saved_mode():
             self._ensure_jump_window()
-        if not self.jump_win:
+        if self.jump_win:
+            winid = self.vim.call("bufwinid", target_buf)
+            if winid > 0:
+                self.vim.call('nvimgdb#KeepCursor', winid)
+        else:
             raise AssertionError("No jump window")
 
         # The terminal buffer may contain the name of the source file
```

**Comment by sakhnik** [comment]
That's a good solution, I like it. Could you please prepare a pull request?
I'd like to run it through the test suite, then we can accept it as is.
But there's a bigger change coming in the branch `lua` (https://github.com/sakhnik/nvim-gdb/commit/fa1e3d98d0ba6623508e6f83b58bc3188b271197). I'll take your change into it.
