### ISSUE TITLE
Question about custom bindings

### ISSUE THREAD

**Issue by MaskRay** [sakhnik/nvim-gdb#39]
I use cgdb a lot and just come across nvim-gdb, think it may integrate well with my LSP workflow. cgdb is not very helpful reading source code due to the lack of cross references. In nvim + LanguageClient-neovim, I can use ccls for definition/references/hover.

Is it easy to turn the following some cgdb bindings into nvim-gdb maps?

```
# `;` switches to the source window
# `i` switches to the command window
imap ; <ESC>

## when the focus is in the source window, the following keys can be used
## they are easier to press compared with <F9> ...
map c :continue<CR>
map d :down<CR>
map f :finish<CR>
map s :step<CR>
map u :up<CR>

map v iinfo<Space>locals<CR><ESC>
```

With cgdb, my cursor mostly stay in the source window. I use `d` `u` `f` `c` a lot, when I need to eval something, I press `i` to switch to the command window, enter `p foo`, press Enter and then `;` to go back to the source window.

Do you have suggestions how I can duplicate the workflow with nvim-gdb? As you see, `p foo` is a time-consuming process. The ideal approach is to stay in the source window, hit some shortcut to evaluate an identifier. https://github.com/cgdb/cgdb/issues/141

By default the gdb window is in the terminal mode (`-- TERMINAL --`). I know `C-\ C-n` enters normal mode but it does not seem very convenient...

I think there are many others who don't like <F9> bindings. You may consider creating a wiki page describing how to bind these commonly used commands to single-letter keys.

**Comment by sakhnik** [comment]
It's pretty easy to define whatever keymaps desired. See which variables could be defined to tune the keymaps: [:help NvimgdbVariables|https://github.com/sakhnik/nvim-gdb/blob/27799810c31efd318886337f811a759eae4f5f51/doc/nvimgdb.txt#L128]. But the use might be to limited for you.

One shortcoming of Vim is that it allows to defined only buffer-local keymaps, not window-local. Thus, this plugin sets and unsets the keymaps dynamically when a source window is entered and left respectively. [The source|https://github.com/sakhnik/nvim-gdb/blob/27799810c31efd318886337f811a759eae4f5f51/autoload/nvimgdb.vim#L395].
Now, I'm thinking whether it's worth implementing customization hooks to allow users to define their own keybindings and workflows. A user would supply his own functions `OnBufEnter`, `OnBufExit`, `OnTermInit`, and the plugin would call them in the right moment. What do you reckon?

By the way, you may use `<esc>` to exit the term mode [in this plugin|https://github.com/sakhnik/nvim-gdb/blob/27799810c31efd318886337f811a759eae4f5f51/autoload/nvimgdb.vim#L285].

**Comment by MaskRay** [comment]
> :help NvimgdbVariables. But the use might be to limited for you.

Instead of a list of `g:nvimgdb_key_until` variables, is it more convenient to have a dictionary `g:nvimgdb_key` and define some common key themes (`s:step; n:next; f:finish ...`)?

But letter keys (`s` `n` ...) are not really able to redefine as it will interfere with normal commands.

> Now, I'm thinking whether it's worth implementing customization hooks to allow users to define their own keybindings and workflows.

I presume you mean to have these keys when the focus is in the source window. I think it should be the best interface.

> tnoremap <silent> <buffer> <esc> <c-\><c-n>

Thanks! With the previous point, I think the debugger window should just stick in terminal mode and all single-key commands should be triggered in the source window.

**Comment by sakhnik** [comment]
Actually, Vim/NeoVim allows you to remap any keys, including built-in commands.
So let me design the interface a little bit first. We need to maintain the backward compatibility, so the individual variables will be maintained for a while.

**Comment by sakhnik** [comment]
The progress can be tracked in the branch `keys`.
