### ISSUE TITLE
module 'gdb.app' not found

### ISSUE THREAD

**Issue by Darkheron** [sakhnik/nvim-gdb#41]
After upgrading this morning I the plugin does not work. Instead much error text is generated centering around a missing gdb.app, eventually ending with:

E5108: Error while calling lua chunk for luaeval(): [string "<VimL compiled string>"]:1: attempt to index global 'gdb' (a nil value) 

I checked the prerequisites, but maybe I missed something.  I can't seem to find this gdb.app lua module anywhere. Is it part of this plugin or something else?  Any tips? It worked great before, and I love this plugin. 

Using NVIM v0.3.1 from the 18.04LTS package from the Ubuntu repos.

**Comment by sakhnik** [comment]
Could you please provide the whole output of `:messages`?

**Comment by sakhnik** [comment]
Are you sure the script `install.sh` finished successfully? Could you please run it manually in a terminal shell?

**Comment by Darkheron** [comment]
Thank you for taking the time to help.
I made progress by running the install.sh manually and finding that lua.h could not be found... even though Plugged indicated it was installed correctly.  After finding the package liblua5.1-0-dev from the repositories progess was made and I can now invoke GdbStart, but I have another problem. 

After invoking GdbStart on the test application you provide: a.out I get the following output in the window:

  File "/home/darkheron/.local/share/nvim/plugged/nvim-gdb/lib/BaseProxy.py", line 153, in Create                         
  13     return BaseProxy(features, args.address, args.cmd)                                                                    
  12   File "/home/darkheron/.local/share/nvim/plugged/nvim-gdb/lib/BaseProxy.py", line 45, in __init__                        
  11     os.execlp(argv[0], *argv)                                                                                             
  10   File "/usr/lib/python3.5/os.py", line 598, in execlp                                                                    
   9     execvp(file, args)                                                                                                    
   8   File "/usr/lib/python3.5/os.py", line 615, in execvp                                                                    
   7     _execvpe(file, args)                                                                                                  
   6   File "/usr/lib/python3.5/os.py", line 660, in _execvpe                                                                  
   5     raise last_exc.with_traceback(tb)                                                                                     
   4   File "/usr/lib/python3.5/os.py", line 650, in _execvpe                                                                  
   3     exec_func(fullname, *argrest)                                                                                         
   2 FileNotFoundError: [Errno 2] No such file or directory                                                                    
   1                                                                                                                           
18   [Process exited 0] 

I don't think this is the full output of the error so I can't figure out what file is missing. Where does the text error dump for this invocation get saved? Any keystroke causes the window to close so I can't yank the whole buffer.. Or is there a command I can use to do such a thing.

**Comment by sakhnik** [comment]
I assumed that `install.sh` should have failed because bash was invoked with `-e`. And the vim-plugged should have propagated the error.
Now, the debugger is started by the proxy script `lib/gdbproxy.py`, that's how it works in both branches: legacy and master. The proxy couldn't launch the debugger because it wasn't reachable in the PATH? Make sure the first argument of the command `:GdbStart` is `gdb`. Try the keystroke `<leader>dd` as an example if you haven't remapped it yet.
