### ISSUE TITLE
E31 NO such mapping

### ISSUE THREAD

**Issue by xbrent** [sakhnik/nvim-gdb#44]
when installed in the beginning. i can debug and saw my code. and F6, F7 step in, out...
and then, after i changed my keymap. there is a E31 error message still happened, even I fallback every.

please help.

 
in my NeoVim RC

38 Plug 'sakhnik/nvim-gdb'         , {'do': './install.sh' }
   39
   40 let g:nvimgdb_config_override = {
   41   \ 'key_next': '<F6>',
   42   \ 'key_step': '<F7>',
   43   \ 'key_finish': '<F4>',
   44   \ 'key_continue': '<F5>',
   45   \ 'key_until': '<F8>',
   46   \ 'key_breakpoint': '<F9>',}
   47
   48 let g:nvimgdb_disable_start_keymaps = 1
   49 nnoremap <leader>dd :GdbStart gdb -q ../bin/iBetter<CR>
   50 nnoremap <leader>ds :GdbDebugStop<CR>

got error
![screen shot 2018-12-26 at 2 54 47 am](https://user-images.githubusercontent.com/3114264/50425871-17569400-08ba-11e9-8670-82099bf6981b.png)

**Comment by xbrent** [comment]
Nvim Config.

![screen shot 2018-12-26 at 3 05 18 am](https://user-images.githubusercontent.com/3114264/50425908-31dd3d00-08bb-11e9-8ce9-d9929db2c808.png)

**Comment by sakhnik** [comment]
Is there anything else relevant in `:messages`?

**Comment by xbrent** [comment]
no other message, 
please check this message output.
![screen shot 2018-12-26 at 3 13 33 am](https://user-images.githubusercontent.com/3114264/50425953-669dc400-08bc-11e9-9f63-37c3f29f7c57.png)

**Comment by sakhnik** [comment]
Right, I can reproduce it. Must be a bug.

**Comment by sakhnik** [comment]
I believe I understand what happened. You redefined `<f9>` to toggle a breakpoint. Meanwhile, the same shortcut was still used to evaluate an expression. Thus, when the plugin tries to unmap keymaps, it fails to do it a second time for `<f9>`. So immediate advice for your config could be to make sure no two keymaps coincide.
I'll think how to properly handle the error meanwhile.

**Comment by xbrent** [comment]
great thanks. I found it.
<img width="874" alt="screen shot 2018-12-26 at 4 57 12 am" src="https://user-images.githubusercontent.com/3114264/50426520-ddda5480-08ca-11e9-9a48-867e66068deb.png">
