### ISSUE TITLE
[enhancement] stop nvimgdb_config_override when in the debug console

### ISSUE THREAD

**Issue by Narice** [sakhnik/nvim-gdb#47]
Hi,
I love the feature of overriding keys for debugging and it's in my point of view extremely useful.
But something that could be great would be to stop the overriding when typing things into the command line. an example would be to just try typing start in the gdb command line after opening the debugging tab. I saw (maybe I'm wrong) that the override is disabled when going to another tab, so I guessed it was feasible.

Thanks for your dedication!

**Comment by sakhnik** [comment]
I can't understand the issue yet. Could you please provide your configuration and the steps to reproduce the problem?

**Comment by sakhnik** [comment]
I see what's going on now, thanks! Let me think how to fix it.

**Comment by sakhnik** [comment]
It turns out it's already possible to suppress the keymaps in the terminal window. So going to update the README.

**Comment by Narice** [comment]
Sorry to bother but I don't really see how what you added in the readme helps.
It seems I didn't understand the solution
I'll try to work it out in the meantime but I'm not sure I'll succeed
just copying what you wrote doesn't work out of the box, I'm surely missing something

**Comment by sakhnik** [comment]
It should work out of the box now. We started from the keys like `s` triggering a GDB command `step` in the debugger window. However, if an (almost) empty hook function `set_tkeymaps` is specified, the plugin won't define normal keymaps in the terminal window.
It tried the config and it works for me.

**Comment by Narice** [comment]
I came back to the plugin today and yes! this works out of the box
Don't really know why it didn't work at the time!
