### ISSUE TITLE
[bug] [no_name] buffer created and kept after GdbDebugStop

### ISSUE THREAD

**Issue by Narice** [sakhnik/nvim-gdb#48]
Hi,
a "ghost" buffer is created or kept after stopping gdb with GdbDebugStop or typing directly in the command line "q".

I hope it's easily fixable

**Comment by sakhnik** [comment]
I'm not sure I understand the issue. Whatever I tried, I couldn't notice any unwanted buffers. Could you please describe the specific steps to reproduce the issue?
[![asciicast](https://asciinema.org/a/222634.svg)](https://asciinema.org/a/222634)

**Comment by Narice** [comment]
I'll try to figure out what's causing it, it might be related to a .vimrc option
could it be related to "set hidden"?

**Comment by Narice** [comment]
for the steps, I'm exactly doing what you did.
And it's a different one from the startup one. 
It adds a new buffer each time I'm leaving gdb.

**Comment by Frederick888** [comment]
Sorry for bumping an old issue but it seems this problem is still reproducible in my case. I'm running neovim v0.4.3 with the latest nvim-gdb and indeed I've got `set hidden` in vimrc. Just thinking out loud here but I wonder whether it's possible to just `bwipe` the buffers used by nvim-gdb during cleanup?

**Comment by sakhnik** [comment]
Yes, probably. The plugin could keep track of the buffers specifically opened for the debugger. But it'll require careful consideration because leaving "ghost" buffers around is a tiny nuisance in comparison to undesirable obliterations. What if a user edits the source code when debugging?

**Comment by Frederick888** [comment]
@sakhnik Then, again please bear with me just making assumptions here, is it possible to use named buffers for nvim-gdb? They don't need to be actually saved somewhere but only used for bufname matching as somewhat a guard during cleanup, e.g. `/tmp/nvim-gdb.session-[0|1|2|...].[src|dbg]`.

**Comment by sakhnik** [comment]
I guess this wouldn't be strictly necessary because the plugin could just remember the buffers. Then we could probably distinguish the modified ones from the untouched ones, skip through the unsaved ones etc. I'll have to experiment around.
