### ISSUE TITLE
[bug] GdbBreakpointToggle doesn't clear enabled breakpoint when not directly on the specific line

### ISSUE THREAD

**Issue by Narice** [sakhnik/nvim-gdb#49]
Hi,
This is a bit of a complex issue to describe but when I'm in the code buffer and doing multiple GdbBreakpointToggle on for example the empty line just before a function, it keeps stacking breakpoints instead of toggling the breakpoint just below.

I guess it might be a bit of a hard issue to resolve, but would solidify greatly the already awesome plugin that you created!

**Comment by sakhnik** [comment]
I'm thinking that this could probably be solved.
* Check whether there already is a breakpoint on the cursor line => nothing in our case
* Set a breakpoint
* See on which line the new breakpoint appeared (we'll need to compare the two states, before and after; depends on #25)
* If it went onto the line whether there was already another breakpoint, send another command to clear the two breakpoints
This could be useful, need to consider it carefully.

**Comment by sakhnik** [comment]
I'm inclined to consider this a non-issue. There is no way to guess where the breakpoint is going to be set without actually placing one. It just sounds right that if a breakpoint is to be deleted, the cursor should be exactly on that line. And finally, to avoid unnecessary complication of the code, I'm closing this ticket.

**Comment by Narice** [comment]
I was wondering if it was the lua part or gdb itself that was causing this behavior
But I guess that yeah, it's pretty difficult to resolve it and with little or no effect on the user experience.
Thanks for checking it out nevertheless!
