### ISSUE TITLE
Frequently hitting "breakpoint.lua:95: connect: No such file or directory"

### ISSUE THREAD

**Issue by lanza** [sakhnik/nvim-gdb#51]
Error detected while processing function <lambda>1:
    line    1:
    E5108: Error while calling lua chunk for luaeval(): ...g/nvim/pack/minpac/start/nvim-gdb/lua/gdb/breakpoint.lua:95: connect: No such file or directory

This happens frequently upon just launching lldb.

Seems like the UDS isn't being created at some point? Can't make sense out of the moonscript syntax to really follow it.

**Comment by sakhnik** [comment]
The function `connect()` is called from [`doQuery()`](https://github.com/sakhnik/nvim-gdb/blob/0c1d17083e31ef33ae1e9ea2360922ffe2702266/lua/gdb/breakpoint.moon#L31). And I left a comment there hinting about the race. The debugger opens the other endpoint asynchronously, and can actually take more time than the client. Especially, if a bigger target is opened.
But when I look at the `doQuery`, it seems to try reconnecting until succeeds. Do breakpoint works for you eventually?
Sorry for the Moonscript, but it's actually easy [to master](http://moonscript.org/reference/), and very helpful in the bigger scale.

**Comment by sakhnik** [comment]
I'm able to simulate the issue. It's obviously bad, and I'm going to fix it.
