### ISSUE TITLE
Readme installation command is not correct

### ISSUE THREAD

**Issue by demantar** [sakhnik/nvim-gdb#60]
I noticed that the command to install the plugin in the readme is not correct, the pipe needs to be escaped with a leading backslash otherwise you get an error (At least it did for me).

The line:
`Plug 'sakhnik/nvim-gdb', { 'do': ':!./install.sh | UpdateRemotePlugins' }`
Should be replaced by:
`Plug 'sakhnik/nvim-gdb', { 'do': ':!./install.sh \| UpdateRemotePlugins' }`

I would have changed it myselve but I dont have much experience with git and all that I know is limited to git itself and not github.

**Comment by sakhnik** [comment]
Thanks, much appreciated!
You'd need to clone the repository to your account, fix the issue in your copy, push (if edited off-line), and create a pull request for me.
