### ISSUE TITLE
Unknown function: GdbInit

### ISSUE THREAD

**Issue by imv** [sakhnik/nvim-gdb#61]
Running GdbStart gdb produces the error:
```
Error detected while processing function nvimgdb#Spawn:
line    1:
E117: Unknown function: GdbInit
```

**Comment by sakhnik** [comment]
Are you sure you run `UpdateRemotePlugins`?

**Comment by imv** [comment]
I did include UpdateRemotePlugins in installation string but it turns out my neovim had no python3 support. Installing pynvim and running UpdateRemotePlugins fixed the issue.

**Comment by T0maas** [comment]
Installing pynvim did not solved problem for me. I have archlinux and I installed folowing packages:
* neovim 0.4.4-1
* python-pynvim 0.4.2-2

When I run UpdateRemotePlugins it gets output:
`function remote#host#UpdateRemotePlugins[6]..<SNR>34_RegistrationCommands[15]..remote#host#Require[10]..provid
er#pythonx#Require[13]..provider#Poll, line 14
Failed to load python3 host. You can try to see what happened by starting nvim with $NVIM_PYTHON_LOG_FILE set
and opening the generated log file. Also, the host stderr is available in messages.
remote/host: generated rplugin manifest: /home/tom/.local/share/nvim/rplugin.vim`

So I set the variable `export NVIM_PYTHON_LOG_FILE=/tmp/err.log` and rerun nvim with UpdateRemotePlugins, but the file did not created.

**Comment by sakhnik** [comment]
@T0maas, it's clearly a pynvim issue. According to their [docs](https://pynvim.readthedocs.io/en/latest/development.html), you'll need to set one more variable: `NVIM_PYTHON_LOG_FILE=logfile NVIM_PYTHON_LOG_LEVEL=DEBUG nvim`.
