### ISSUE TITLE
Colors in gdb split

### ISSUE THREAD

**Issue by mightymicha** [sakhnik/nvim-gdb#62]
Hey, I saw that its possible to colorize the gdb output with a .gdbinit file like [this](https://gist.github.com/CocoaBeans/1879270) or [this](https://github.com/gdbinit/gdbinit) one. Using this with nvim-gdb, my source window stays empty. Is it possible to use such a config file with nvim-gdb?

**Comment by sakhnik** [comment]
That's a good idea! To support colours, we just need to skip escape sequences when parsing the debugger output in `scm.py` before feeding it to the regexp matchers. Would you be able to implement this and create a pull request?

**Comment by sakhnik** [comment]
All right, I tried your code and realized what happens. GDB is actually run in a PTY by an auxiliary program `gdbproxy.py`. It conceals service commands issued by the plugin from the user. Basically, it cuts everything between `server info breakpoints` and `(gdb)` out, while letting through everything else.
Having changed the prompt, we left the proxy in the closed state forever.

Reference: https://github.com/sakhnik/nvim-gdb/blob/da5819e0b83ed2e50436e0406e1bcb445ab1f4ea/lib/gdbproxy.py#L18

There is a bug in this program that it stays filtering forever. It should probably stop filtering after some timeout.

We could potentially extend the terminator `PROMPT` to skip escape sequences when looking for a match. Or teach the program to adapt to the current prompt more intelligently.

**Comment by sakhnik** [comment]
@mightymicha, I solved this issue using `gdb.prompt_hook` to mark the prompt. Now the program doesn't care about the shape of the GDB prompt assuming no one overrides the hook.
