### ISSUE TITLE
support vim

### ISSUE THREAD

**Issue by epheien** [sakhnik/nvim-gdb#65]
vim can support rplugin via some compatible layer, like deoplete and ncm2
Can nvim-gdb support vim?

**Comment by sakhnik** [comment]
This becomes a frequent question: see #55, for instance. I believe the plugin __can__ be ported to Vim8, but the change wouldn't be straight forward. I'm quite satisfied with NeoVim, so I'm not going to do the porting. But if anyone did it, I'd happily accept a pull request. Could you do that?

**Comment by epheien** [comment]
I just write a similar plugin https://github.com/epheien/termdbg use raw vimL.
I prefer vimL for debugger pluggin, because I think, debugger is not performance sensitive.
But I have not much free time to support lldb and gdb.
With newer gdb version, gdb has a new-ui interface for debugger intergrate with vim, see `:h terminal-debug` in vim8.1.

If I have enough free time, I will try to port to vim8.1.

**Comment by sakhnik** [comment]
The code has gradually become more and more neovim-specific. I don't think it'll ever be ported to Vim.
