### ISSUE TITLE
gdb remote server

### ISSUE THREAD

**Issue by abouteiller** [sakhnik/nvim-gdb#68]
It does not appear to be possible to **invoke gdb on a remote server:** 

`:GdbStart ssh -t node12 gdb -p 7259` yields incorrect results 

```
Warning: Identity file x not accessible: no such file or directory.
Pseudo-terminal will not be allocated because stdin is not a terminal.
ssh_exchange_identification: Connection closed by remote host
```

Looking at how the gdbwrap.sh script works, it looks like this capability is not possible. I think it would be grand if it were possible.

**Comment by sakhnik** [comment]
Thanks for the report and suggestion!
`:GdbStart` assumes the first command is gdb, not ssh. So incorrect command is formed. Another issue is to supply custom gdbinit. Not an issue on a local file system, but wouldn't work as-is for ssh.
I'll have to experiment a little bit to find a good solution.

**Comment by sakhnik** [comment]
I believe this won't be fixed any soon. Consider the development environment:
- If the whole development environment is available in the target, you could just ssh into a terminal, setup neovim there and use the plugin as if from a local shell.
- If the source code isn't available in the target, why would you run `gdb` there in the first place?
- If the source code is on the host, people usually run `gdbserver` in the target, and have the conventional debugging experience by launching `gdb` on the host and connecting to the server. The plugin supports this.

If we were fixing the issue, the following would need to be resolved:
- Investigate and fix the PTY issue
- Fix GDB custom initialization (the plugin runs on the host, the gdb is launched on the target, the init script should be where the GDB is)
