### ISSUE TITLE
Change the architecture to not be coupled to a specific window?

### ISSUE THREAD

**Issue by lanza** [sakhnik/nvim-gdb#74]
I occasionally hit bugs where nvim-gdb looks at the window that was originally tied to the nvim-gdb instance and dies and spams errors if it's gone or some other hard to trace condition causes one of the exit functions to be called. One of the design goals for working on a debugger is that it should NEVER fail. Debugging bugs should never fail due to bugs. Debuggers should be incredibly reliable. If it hits an internal bug it should try to fix itself. If a condition fails it should fix it. If the debugger shuts down it should be because the user shut it down. 

So I was thinking a different approach would be to remove the `apps` `dict` and just have one `app` and decouple it from specific `Window`. If `jumpWin` is gone, make a new one. If the terminal win is gone, open a new one. The only condition for the debugging session to fail should be if the debugger process has exited. 

Any thoughts?

**Comment by sakhnik** [comment]
Yes, I agree with you. The multi-debugging support was added just to make sure that all the keymaps are properly defined/undefined when the user navigates between tabs.
But I really doubt anyone could use a couple of debuggers simultaneously. The change should be easy.
However, we should carefully consider what to do with the jump window closed. Currently, we allow finishing debugging session completely if either terminal or jump window is closed. That was a feature, not a bug.

**Comment by sakhnik** [comment]
All right, let's look at the proposal. When the terminal window is gone, the debugger process loses the terminal and is terminated with `SIGHUP`. So I suggest accepting this as-is for now (some terminal session management like in tmux could be implemented in theory).
When the jump window is accidentally closed, we could change the program to restore it though.

**Comment by sakhnik** [comment]
It turns out that when the terminal window is closed, the terminal buffer is gone too. There is no point in keeping the tab then.
