### ISSUE TITLE
Bug when unsetting overridden keys

### ISSUE THREAD

**Issue by palmenros** [sakhnik/nvim-gdb#75]
I really love overriding keys for debugging and I think it is very useful. If I run `:GdbStart` and then I change to the source code window, and back into the gdb window, then, when closing gdb, the keymap is the usual one (the one I defined for not debugging purposes).

However, if I don't ever change windows into the source code windows and I exit gdb, then the debugging keymaps continue being there, causing errors such as `E492: Not an editor command: GdbUntil`

Is there a way to recover my original keymaps without having to change to the source code window?

Thanks

**Comment by palmenros** [comment]
I found a workaround by calling on `App.cleanup` `self.keymaps.dispatchUnset()`, which fixed the issue. As I am not familiar with this codebase, I am afraid of making a pull request, because I don't know what side effects that change could cause. If you could verify if it is safe and make the change, I would greatly appreciate it, as I could continue updating the plugin.

Thanks

**Comment by sakhnik** [comment]
You're right! Normally, `dispatchSet()` and `dispatchUnset()` should be consistent with your navigation. Whenever you focus the jump window, the `dispatchSet()` is called defining mappings, and when you leave, the other one is called. But since you never navigated, the keymaps shouldn't have been redefined. That's what needs be investigated.

**Comment by sakhnik** [comment]
All right, I couldn't reproduce your issue. You see, the stock keymaps are defined with `<buffer>`. So they are unlikely to survive the debugging session.
Could you please describe more details about your config?

**Comment by palmenros** [comment]
Yes, you can see my entire config here: https://github.com/palmenros/dotfiles/blob/master/nvim/

**Comment by palmenros** [comment]
I have noticed that the issue happens when you call `GdbStart` from a file which is not opened during debugging. For example, if you call `GdbStart` on `CMakeLists.txt` and then debugging you only navigate in `Main.cpp` for example, when you return to `CMakeLists.txt` after debugging, the debugging keymap continue to be overriden

**Comment by sakhnik** [comment]
Apparently, that was a bug after #70 . Executing `doautoa BufEnter` causes nvim-gdb defining keymaps in ever buffer!

**Comment by palmenros** [comment]
Thank you! That fixed the issue
