### ISSUE TITLE
Send quit to GDB after ending debugging session

### ISSUE THREAD

**Issue by palmenros** [sakhnik/nvim-gdb#76]
I am trying to save breakpoints at the end of the debugging session and load them afterwards in the next debugging session. For that I use GDB `save breakpoints`, which I call from `hook-quit`. It is called whenever I use `quit`, however, if I exit the debugging session using `GdbDebugStop` or by exiting the window by pressing `:q`.

Is there a way to send gdb the `quit` command before exiting, so my custom hook is called and the breakpoint can be saved?

Thanks

**Comment by sakhnik** [comment]
Unfortunately, we can't guarantee that `quit` will be called in all scenarios. Could you please try a different handler instead: https://stackoverflow.com/questions/29487307/how-to-detect-gdb-exit-via-hooks-in-gdbs-mi-interpreter-mode ?

**Comment by palmenros** [comment]
Using `atexit` hook worked flawlessly. Thank you!

**Comment by vtronko** [comment]
@palmenros can you please share your result?
