### ISSUE TITLE
breakpoint saving

### ISSUE THREAD

**Issue by lanza** [sakhnik/nvim-gdb#78]
Something most IDEs do is save breakpoints between debugging sessions. This would be a neat feature to continuously write breakpoints to file as they are requested in nvim-gdb itself. I say continuously, though, because there's no guarantee the shutdown code ever gets called so you wouldn't want to rely on it.

**Comment by sakhnik** [comment]
It's possible to achieve already, just like in #76. Our debuggers (GDB, LLDB) are already scriptable enough to fit them into any custom workflow, aren't they?
