### ISSUE TITLE
Bug when exiting gdb

### ISSUE THREAD

**Issue by palmenros** [sakhnik/nvim-gdb#79]
When exiting GDB, the following error appears in the terminal:

```
Traceback (most recent call last):
File "/home/pedro/.config/nvim/plugged/nvim-gdb/lib/BaseProxy.py", line 81, in run self._process()
File "/home/pedro/.config/nvim/plugged/nvim-gdb/lib/BaseProxy.py", line 146, in _processdata = os.read(self.master_fd, 1024)
OSError: [Errno 5] Input/output error
```
This error appeared after commit `56463d089e92d77ef4fcb31303ff65e7a58957fb`

**Comment by sakhnik** [comment]
Interesting, I've never experienced this one. Would you be able to debug it or describe a good scenario for me to reproduce it?

**Comment by palmenros** [comment]
I don't know how to debug that python code. Playing with the commits, I have discovered that the bug was introduced in commit `0013fa23b8c2fe0bcc7659df8ea87c8aa652ba9c` to branch `devel`. Maybe that is helpful.

**Comment by sakhnik** [comment]
All right, the change allowed showing exceptions in the terminal as opposed to just logging them concealed. I can't still reproduce the issue, so probably it's a kind of race. But I have an idea of how to fix this one.
