### ISSUE TITLE
Support remake -- make debugger

### ISSUE THREAD

**Issue by lanza** [sakhnik/nvim-gdb#80]
[`remake`](http://bashdb.sourceforge.net/remake/) is to `make` what `bashdb` is to `bash`. They are written by the same guy and have similar interfaces and output. Adding this shouldn't be too cumbersome beyond `bashdb`. 

Also worth noting is that we should probably have a more decoupled path for extending with additional debuggers. Maybe a base class called `Debugger` which you subclass and `Debugger.registerPlugin("remake")` which will call a method on the parent class and fills out all information.

I started playing with adding remake and found the grep + read + search + find matching functions to be a relatively burdensome process.

**Comment by sakhnik** [comment]
Interesting! Let me see it when it's ready!
