### ISSUE TITLE
Support vim filename placeholder in GdbStart

### ISSUE THREAD

**Issue by bvolkmer** [sakhnik/nvim-gdb#82]
It would be nice to use something like:

    :GdbStart gdb -q %:r

(here: running gdb on the current file without file-extensions)
I.e. using the filename placeholder syntax of vim inside the GdbStart command.

Currently it is passed as it is to gdb, resulting in gdb no finding the file "%:r".

**Comment by sakhnik** [comment]
That's a good idea! Do you have any idea how to fix the plugin?
