### ISSUE TITLE
Error on GdbStartLLDB

### ISSUE THREAD

**Issue by CallumHoward** [sakhnik/nvim-gdb#9]
Hi,

I'm getting the following errors when starting GdbStartLLDB with a simple .c program.
```
"allEven.c" 47L, 1090C
Error detected while processing function <SNR>107_JobOutput[1]..31[15]..32[13]..<SNR>106_GdbRunning_pause[7]..24:
line    1:
E117: Unknown function: chansend
Error detected while processing function <SNR>107_JobOutput[1]..31[15]..32[13]..<SNR>106_GdbRunning_pause[7]..24:
line    1:
E117: Unknown function: chansend
Error detected while processing function <SNR>107_JobOutput[1]..31[15]..32[13]..<SNR>106_GdbRunning_pause[7]..24:
line    1:
E117: Unknown function: chansend
Error detected while processing function <SNR>107_JobOutput[1]..31[15]..32[13]..<SNR>106_GdbRunning_pause[7]..24:
line    1:
E117: Unknown function: chansend
```

I am on macOS.  
lldb --version  ==  lldb-900.0.64

**Comment by sakhnik** [comment]
Right, I substituted deprecated `jobsend()` with `chansend()` [recently](https://github.com/sakhnik/nvim-gdb/commit/27cb4a50c67a3162d4a5b4e4a9249dd0b28d2e55). The API changed in neovim couple of months ago: [RFC](https://github.com/neovim/neovim/pull/6844/commits).
Reverting the change for now.
