### ISSUE TITLE
Terminal doesn't scroll to bottom by default

### ISSUE THREAD

**Issue by Frederick888** [sakhnik/nvim-gdb#90]
Tested against GDB and PDB and were able to reproduced this issue with both of them (guess it's not debugger-specific).

After debugger starts, if I go directly back to source code and start debugging, terminal will not automatically scroll to bottom even if the output overflows. I have to enter insert mode in terminal once to make the scrolling work.

My configuration:
```vim
let g:nvimgdb_config_override = {
    \ 'key_next': '<F10>',
    \ 'key_step': '<F11>',
    \ 'key_finish': '<F23>',
    \ 'key_continue': '<F5>',
    \ 'key_until': '<F4>',
    \ 'key_breakpoint': '<F9>',
    \ 'key_eval': '<Leader>e',
    \ }
```

Neovim version:
```
NVIM v0.4.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.2/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by sakhnik** [comment]
I've just noticed that the terminal buffer is followed automatically if the cursor is placed on the last line of the terminal window (`G`). And it keeps doing so even after I go to the jump window with the source code. Have you tried this in your case?

**Comment by Frederick888** [comment]
Yes, I can confirm that if I hit `G` in terminal first then the auto scrolling works when it overflows. May I know whether this can be made the default behaviour?

**Comment by sakhnik** [comment]
It does make sense. Let's hard code it. We'll be able to add an option later if anyone asks.
