### ISSUE TITLE
[lldb] Unicode and Python 3

### ISSUE THREAD

**Issue by foonathan** [sakhnik/nvim-gdb#93]
My python version of lldb got upgraded to python 3, which meant I got an error in https://github.com/sakhnik/nvim-gdb/blob/master/lib/lldb_commands.py#L64. Removing the `.encode('ascii')` fixes it for me, but I don't know how to handle it for python 2 as well.

**Comment by sakhnik** [comment]
Thanks for letting me know! Apparently, `.decode('ascii')` was necessary to correctly coerce types in the C++ API. So I had to introduce a version check.
