### ISSUE TITLE
Scrolling through history messes up prompt

### ISSUE THREAD

**Issue by hereGittyGitty** [sakhnik/nvim-gdb#98]
When scrolling through history, the `gdb` prompt gets messed up with remaining artifacts. Have a look at this _gif_:
![nvim-gdb](https://user-images.githubusercontent.com/2407498/69195432-eadbe400-0b2b-11ea-9488-76cdf2e61aa9.gif)
I am using _gnome-terminal_.

Thx for that plugin though. :)

**Comment by sakhnik** [comment]
That's a tricky one because GDB is run in a PTY through a proxy app.

**Comment by hereGittyGitty** [comment]
Happens here on different machines running different Linux Operating Systems and actually fairly often. My first attempt was to change the following line in  the `gdb_wrap.sh`
```
python gdb.prompt_hook = lambda p: p + ("" if p.endswith("\x1a\x1a\x1a") else "\x1a\x1a\x1a")
```
without much luck.  If I can help you somehow just ask.

**Comment by sakhnik** [comment]
Yes, this line just puts a marker for the proxy app to recognize prompt.
I suspect that that's the history of commands that matters. Could you please notice what exact commands cause the mess?

**Comment by hereGittyGitty** [comment]
Being on the _gdb_ command prompt I only have to do the following to get the artifacts:

1. type `info program` and press `<enter>`
2. press `<Arrow up` to get the latest command from history (i.e. `info program`)
3. press `Arrow down` to get an empty prompt again.  

Instead of an empty prompt (`(gdb) `), I get `(gdb) inf`.

By the way:

Changing the line in the `gdb_wrap.sh` mentioned above from

```python
python gdb.prompt_hook = lambda p: p + ("" if p.endswith("\x1a\x1a\x1a") else "\x1a\x1a\x1a")
```
to

```python
python gdb.prompt_hook = lambda p: p + ("" if p.endswith("\x1a\x1a\x1a") else "")
```
seems to fix the artifacts error, but creates a bunch of other ones.

**Comment by sakhnik** [comment]
I appreciate your effort, but I still can't reproduce the issue. There's what I see when run neovim in alacritty + tmux:
[![asciicast](https://asciinema.org/a/282878.svg)](https://asciinema.org/a/282878)

**Comment by sakhnik** [comment]
In fact, I've tried alacritty and gnome-terminal without tmux. Yet still, the prompt is clean.
It's in Arch Linux, by the way.

**Comment by hereGittyGitty** [comment]
Hmm...  then it does only affect me. I must be something special ;).
You can close the issue. Thanks a lot for your help.

Just for the records:

I am here on _Gentoo_ and _Ubuntu 16.04.6 LTS_ and tried it with _gnome-terminal_ and _xterm_.

Cya. :)

**Comment by hereGittyGitty** [comment]
Funny. Guess that this is no good practice but I just found out that I do not have the problem when start _nvim_ Like this:

```bash
LANG=C nvim
```
Must be some kind of _locale_ problem.

**Comment by anstadnik** [comment]
I have the same problem using Arch, kitty, and nvim.
Here is the minimal `init.vim`:
```vim
call plug#begin()
Plug 'sakhnik/nvim-gdb',                { 'for': ['c', 'cpp'], 'do': ':!./install.sh \| UpdateRemotePlugins'  }
call plug#end()
nnoremap <leader><leader><CR> :GdbStart gdb -q ~/my/secret/path
```
output of `nvim -v`
```NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.3/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info```

**Comment by sakhnik** [comment]
Hm, I still can't reproduce the issue with Ukrainian locale enabled in alacritty/tmux.
[![asciicast](https://asciinema.org/a/283267.svg)](https://asciinema.org/a/283267)

Will try kitty later.

**Comment by hereGittyGitty** [comment]
Hi,
you should get the error when starting `nvim` like this in _gnome_terminal_

```bash
LANG=en_US.utf8 /usr/bin/nvim
```
assuming your `nvim` executable is located in `/usr/bin`.

**Comment by sakhnik** [comment]
Maybe, but I don't (get it). The result is the same as with `uk_UA.UTF-8`.
